=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/residences/residence.dtd
<!ELEMENT residence (support|item_create|restore_exp|restore_hp|restore_mp|teleport|platform|curtain|skills|banish_points|owner_restart_points|other_restart_points|chaos_restart_points|related_fortresses|merchant_guards)*>
<!ATTLIST residence
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	impl CDATA #REQUIRED
	rental_fee CDATA #IMPLIED
	min_bid CDATA #IMPLIED
	deposit CDATA #IMPLIED
	grade CDATA #IMPLIED>
<!ELEMENT support (#PCDATA)>
<!ATTLIST support
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT item_create (#PCDATA)>
<!ATTLIST item_create
	level CDATA #REQUIRED
	npcId CDATA #REQUIRED
	listId CDATA #REQUIRED
	lease CDATA #REQUIRED>
<!ELEMENT restore_exp (#PCDATA)>
<!ATTLIST restore_exp
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT platform (#PCDATA)>
<!ATTLIST platform
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT curtain (#PCDATA)>
<!ATTLIST curtain
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT restore_hp (#PCDATA)>
<!ATTLIST restore_hp
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT restore_mp (#PCDATA)>
<!ATTLIST restore_mp
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT teleport (target)*>
<!ATTLIST teleport
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	loc CDATA #REQUIRED
	name CDATA #REQUIRED
	price CDATA #REQUIRED
	StringName CDATA #REQUIRED
	StringNameLang CDATA #REQUIRED>
<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT banish_points (point)*>
<!ELEMENT owner_restart_points (point)*>
<!ELEMENT other_restart_points (point)*>
<!ELEMENT chaos_restart_points (point)*>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT related_fortresses (domain|boundary)*>
<!ELEMENT domain (#PCDATA)>
<!ATTLIST domain
	fortress CDATA #REQUIRED>
<!ELEMENT boundary (#PCDATA)>
<!ATTLIST boundary
	fortress CDATA #REQUIRED>
<!ELEMENT merchant_guards (merchant_guard)*>
<!ELEMENT merchant_guard (#PCDATA)>
<!ATTLIST merchant_guard
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	max CDATA #REQUIRED
	ssq CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/residences/[41] the_bronze_chamber.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="41" name="The Bronze Chamber" impl="ClanHall" grade="50" rental_fee="5000000" min_bid="50000000" deposit="1500000">
	<support level="3" lease="7000"/>
	<support level="13" lease="70000"/>
	<support level="5" lease="21000"/>
	<support level="15" lease="210000"/>
	<support level="7" lease="37000"/>
	<support level="17" lease="370000"/>
	<support level="8" lease="52000"/>
	<support level="18" lease="520000"/>
	<item_create level="1" npcId="35449" listId="50066" lease="30000"/>
	<item_create level="2" npcId="35449" listId="50067" lease="70000"/>
	<item_create level="3" npcId="35449" listId="50068" lease="140000"/>
	<curtain level="1" lease="286"/>
	<curtain level="2" lease="375"/>
	<platform level="1" lease="433"/>
	<platform level="2" lease="1333"/>
	<restore_exp level="15" lease="3000"/>
	<restore_exp level="25" lease="9000"/>
	<restore_exp level="35" lease="18000"/>
	<restore_exp level="50" lease="18000"/>
	<restore_hp level="80" lease="1000"/>
	<restore_hp level="120" lease="1500"/>
	<restore_hp level="180" lease="2250"/>
	<restore_hp level="240" lease="3750"/>
	<restore_hp level="300" lease="5166"/>
	<restore_mp level="5" lease="2000"/>
	<restore_mp level="15" lease="6500"/>
	<restore_mp level="30" lease="13750"/>
	<restore_mp level="40" lease="20000"/>
	<teleport level="1" lease="1000">
		<target loc="147450 28081 -2294" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="151950 25094 -2172" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="142593 26344 -2425" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
		<target loc="147503 32299 -2501" name="1010028" price="0" StringName="South Gate Entrance" StringNameLang="Южные врата"/><!--South Gate Entrance-->
		<target loc="147465 20737 -2130" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
	</teleport>
	<teleport level="2" lease="2000">
		<target loc="147450 28081 -2294" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="151950 25094 -2172" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="142593 26344 -2425" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
		<target loc="147503 32299 -2501" name="1010028" price="0" StringName="South Gate Entrance" StringNameLang="Южные врата"/><!--South Gate Entrance-->
		<target loc="147465 20737 -2130" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
		<target loc="106517 -2871 -3454" name="1010127" price="500" StringName="Ancient Battleground" StringNameLang="Древнее Поле Битвы"/><!--Ancient Battleground-->
		<target loc="124904 61992 -3973" name="1010618" price="500" StringName="Enchanted Valley, Southern Region" StringNameLang="Волшебная Долина - юг"/><!--Enchanted Valley, Southern Region-->
		<target loc="104426 33746 -3825" name="1010619" price="500" StringName="Enchanted Valley, Northern Region" StringNameLang="Волшебная Долина - север"/><!--Enchanted Valley, Northern Region-->
		<target loc="155310 -16339 -3320" name="1010060" price="500" StringName="Blazing Swamp" StringNameLang="Раскаленные Топи"/><!--Blazing Swamp-->
		<target loc="142065 81300 -3000" name="1010585" price="500" StringName="Forest of Mirrors" StringNameLang="Лес Зеркал"/><!--Forest of Mirrors-->
		<target loc="166182 91560 -3168" name="1010607" price="500" StringName="Anghel Waterfall" StringNameLang="Ангельский Водопад"/><!--Anghel Waterfall-->
		<target loc="181726 -7524 -3464" name="1010137" price="500" StringName="South Entrance of Devastated Castle" StringNameLang="Южный Вход в Разоренный Замок"/><!--South Entrance of Devastated Castle-->
		<target loc="168779 -18790 -3184" name="1010192" price="500" StringName="West Area of the Devastated Castle" StringNameLang="Запад Разоренного Замка"/><!--West Area of the Devastated Castle-->
		<target loc="184742 19745 -3168" name="1010604" price="500" StringName="Seal of Shilen" StringNameLang="Запретные Врата"/><!--Seal of Shilen-->
		<target loc="168217 37990 -4072" name="1010143" price="500" StringName="Forsaken Plains" StringNameLang="Забытые Равнины"/><!--Forsaken Plains-->
		<target loc="114649 11115 -5120" name="1010144" price="500" StringName="Tower of Insolence" StringNameLang="Башня Дерзости"/><!--Tower of Insolence-->
		<target loc="183985 61424 -3992" name="1010702" price="500" StringName="The Giant's Cave Upper Layer" StringNameLang="Верхний Этаж Пещеры Гигантов"/><!--The Giant's Cave Upper Layer-->
		<target loc="191754 56760 -7624" name="1010703" price="500" StringName="The Giant's Cave Lower Layer" StringNameLang="Нижний Этаж Пещеры Гигантов"/><!--The Giant's Cave Lower Layer-->
	</teleport>
	<banish_points>
		<point x="144448" y="28384" z="-2256" />
	</banish_points>
	<owner_restart_points>
		<point x="144014" y="28202" z="-2280" />
	</owner_restart_points>
	<other_restart_points>
		<point x="144448" y="28384" z="-2256" />
	</other_restart_points>
	<chaos_restart_points>
	</chaos_restart_points>
</residence>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/residences/[43] the_silver_chamber.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="43" name="The Silver Chamber" impl="ClanHall" grade="50" rental_fee="5000000" min_bid="50000000" deposit="1500000">
	<support level="3" lease="7000"/>
	<support level="13" lease="70000"/>
	<support level="5" lease="21000"/>
	<support level="15" lease="210000"/>
	<support level="7" lease="37000"/>
	<support level="17" lease="370000"/>
	<support level="8" lease="52000"/>
	<support level="18" lease="520000"/>
	<item_create level="1" npcId="35453" listId="50003" lease="30000"/>
	<item_create level="2" npcId="35453" listId="50004" lease="70000"/>
	<item_create level="3" npcId="35453" listId="50005" lease="140000"/>
	<curtain level="1" lease="286"/>
	<curtain level="2" lease="375"/>
	<platform level="1" lease="433"/>
	<platform level="2" lease="1333"/>
	<restore_exp level="15" lease="3000"/>
	<restore_exp level="25" lease="9000"/>
	<restore_exp level="35" lease="18000"/>
	<restore_exp level="50" lease="18000"/>
	<restore_hp level="80" lease="1000"/>
	<restore_hp level="120" lease="1500"/>
	<restore_hp level="180" lease="2250"/>
	<restore_hp level="240" lease="3750"/>
	<restore_hp level="300" lease="5166"/>
	<restore_mp level="5" lease="2000"/>
	<restore_mp level="15" lease="6500"/>
	<restore_mp level="30" lease="13750"/>
	<restore_mp level="40" lease="20000"/>
	<teleport level="1" lease="1000">
		<target loc="81749 149171 -3464" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="81525 143821 -3528" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
		<target loc="88342 147329 -3400" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="81548 152633 -3528" name="1010028" price="0" StringName="South Gate Entrance" StringNameLang="Южные врата"/><!--South Gate Entrance-->
		<target loc="77305 148636 -3592" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
	</teleport>
	<teleport level="2" lease="2000">
		<target loc="81749 149171 -3464" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="81525 143821 -3528" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
		<target loc="88342 147329 -3400" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="81548 152633 -3528" name="1010028" price="0" StringName="South Gate Entrance" StringNameLang="Южные врата"/><!--South Gate Entrance-->
		<target loc="77305 148636 -3592" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
		<target loc="85546 131328 -3672" name="1010118" price="500" StringName="Breka's Stronghold" StringNameLang="Укрепление Бреки"/><!--Breka's Stronghold-->
		<target loc="43408 206881 -3752" name="1010152" price="500" StringName="Devil's Isle" StringNameLang="Остров Дьявола"/><!--Devil's Isle-->
		<target loc="73024 118485 -3720" name="1010067" price="500" StringName="Dragon Valley" StringNameLang="Долина Драконов"/><!--Dragon Valley-->
		<target loc="60374 164301 -2856" name="1010115" price="500" StringName="Tanor Canyon" StringNameLang="Каньон Танор"/><!--Tanor Canyon-->
	</teleport>
	<banish_points>
		<point x="83409" y="148578" z="-3300" />
	</banish_points>
	<owner_restart_points>
		<point x="82032" y="145328" z="-3520" />
	</owner_restart_points>
	<other_restart_points>
		<point x="83409" y="148578" z="-3300" />
	</other_restart_points>
	<chaos_restart_points>
	</chaos_restart_points>
</residence>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/residences/[108] white_sands_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="108" name="White Sands Fortress" impl="Fortress">
	<support level="7" lease="49000"/>
	<support level="17" lease="490000"/>
	<support level="8" lease="120000"/>
	<support level="18" lease="1200000"/>
	<restore_exp level="45" lease="63000"/>
	<restore_exp level="50" lease="70000"/>
	<restore_hp level="300" lease="12000"/>
	<restore_hp level="400" lease="20000"/>
	<restore_mp level="40" lease="45000"/>
	<restore_mp level="50" lease="65000"/>
	<teleport level="1" lease="1000">
		<target loc="116336 203775 -3336" name="1010656" price="0" StringName="Fortress West Gate" StringNameLang="Западные врата Крепости"/><!--Fortress West Gate-->
		<target loc="120487 206093 -3336" name="1010657" price="0" StringName="Fortress East Gate" StringNameLang="Восточные врата Крепости"/><!--Fortress East Gate-->
		<target loc="111455 219400 -3546" name="1010686" price="0" StringName="Heine Town Square" StringNameLang="Площадь Хейна"/><!--Heine Town Square-->
		<target loc="117608 241660 -1408" name="1010684" price="0" StringName="Front of the Innadril Castle Gate" StringNameLang="Врата Замка Иннадрил"/><!--Front of the Innadril Castle Gate-->
	</teleport>
	<teleport level="2" lease="10000">
		<target loc="116336 203775 -3336" name="1010656" price="0" StringName="Fortress West Gate" StringNameLang="Западные врата Крепости"/><!--Fortress West Gate-->
		<target loc="120487 206093 -3336" name="1010657" price="0" StringName="Fortress East Gate" StringNameLang="Восточные врата Крепости"/><!--Fortress East Gate-->
		<target loc="111455 219400 -3546" name="1010686" price="0" StringName="Heine Town Square" StringNameLang="Площадь Хейна"/><!--Heine Town Square-->
		<target loc="117608 241660 -1408" name="1010684" price="0" StringName="Front of the Innadril Castle Gate" StringNameLang="Врата Замка Иннадрил"/><!--Front of the Innadril Castle Gate-->
		<target loc="80987 182423 -3504" name="1010704" price="500" StringName="Field of Silence Center" StringNameLang="Сердце Полей Безмолвия"/><!--Field of Silence Center-->
		<target loc="86147 218268 -3592" name="1010705" price="500" StringName="Field of Whispers Center" StringNameLang="Сердце Шепчущих Полей"/><!--Field of Whispers Center-->
		<target loc="113708 178387 -3232" name="1010606" price="500" StringName="The Center of Alligator Island" StringNameLang="Центр Острова Аллигаторов"/><!--The Center of Alligator Island-->
		<target loc="82693 242220 -6712" name="1010526" price="500" StringName="Inside the Garden of Eva" StringNameLang="Внутри Садов Богини Евы"/><!--Inside the Garden of Eva-->
	</teleport>
	<skills>
		<skill id="592" level="1" /> <!--Residence Soul-->
		<skill id="599" level="1" /> <!--Residence Magic Barrier-->
	</skills>
	<banish_points>
		<point x="124651" y="207877" z="-3184" />
		<point x="124482" y="207906" z="-3192" />
		<point x="113959" y="201830" z="-3488" />
		<point x="114053" y="201766" z="-3496" />
	</banish_points>
	<owner_restart_points>
		<point x="118740" y="204589" z="-3008" />
		<point x="118598" y="204592" z="-3008" />
		<point x="118468" y="204458" z="-3008" />
	</owner_restart_points>
	<other_restart_points>
		<point x="107568" y="218256" z="-3624" />
		<point x="107920" y="218240" z="-3624" />
		<point x="107808" y="217856" z="-3624" />
		<point x="108032" y="218048" z="-3624" />
		<point x="107552" y="218000" z="-3624" />
		<point x="110912" y="219584" z="-3624" />
		<point x="110768" y="219824" z="-3624" />
		<point x="110688" y="220576" z="-3624" />
		<point x="110896" y="220768" z="-3624" />
		<point x="111856" y="220752" z="-3624" />
		<point x="112112" y="220576" z="-3624" />
		<point x="112064" y="219792" z="-3624" />
		<point x="111888" y="219584" z="-3624" />
	</other_restart_points>
	<chaos_restart_points>
		<point x="117872" y="225536" z="-3200" />
		<point x="118064" y="225648" z="-3200" />
		<point x="101696" y="221808" z="-3520" />
		<point x="101552" y="221568" z="-3520" />
		<point x="100784" y="218272" z="-3420" />
		<point x="100928" y="218560" z="-3420" />
	</chaos_restart_points>

</residence>
