=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/residences/residence.dtd
<!ELEMENT residence (support|item_create|restore_exp|restore_hp|restore_mp|teleport|platform|curtain|skills|banish_points|owner_restart_points|other_restart_points|chaos_restart_points|related_fortresses|merchant_guards)*>
<!ATTLIST residence
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	impl CDATA #REQUIRED
	rental_fee CDATA #IMPLIED
	min_bid CDATA #IMPLIED
	deposit CDATA #IMPLIED
	grade CDATA #IMPLIED>
<!ELEMENT support (#PCDATA)>
<!ATTLIST support
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT item_create (#PCDATA)>
<!ATTLIST item_create
	level CDATA #REQUIRED
	npcId CDATA #REQUIRED
	listId CDATA #REQUIRED
	lease CDATA #REQUIRED>
<!ELEMENT restore_exp (#PCDATA)>
<!ATTLIST restore_exp
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT platform (#PCDATA)>
<!ATTLIST platform
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT curtain (#PCDATA)>
<!ATTLIST curtain
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT restore_hp (#PCDATA)>
<!ATTLIST restore_hp
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT restore_mp (#PCDATA)>
<!ATTLIST restore_mp
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT teleport (target)*>
<!ATTLIST teleport
	lease CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	loc CDATA #REQUIRED
	name CDATA #REQUIRED
	price CDATA #REQUIRED
	StringName CDATA #REQUIRED
	StringNameLang CDATA #REQUIRED>
<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT banish_points (point)*>
<!ELEMENT owner_restart_points (point)*>
<!ELEMENT other_restart_points (point)*>
<!ELEMENT chaos_restart_points (point)*>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT related_fortresses (domain|boundary)*>
<!ELEMENT domain (#PCDATA)>
<!ATTLIST domain
	fortress CDATA #REQUIRED>
<!ELEMENT boundary (#PCDATA)>
<!ATTLIST boundary
	fortress CDATA #REQUIRED>
<!ELEMENT merchant_guards (merchant_guard)*>
<!ELEMENT merchant_guard (#PCDATA)>
<!ATTLIST merchant_guard
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	max CDATA #REQUIRED
	ssq CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/residences/[48] onyx_hall.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="48" name="Onyx Hall" impl="ClanHall" grade="50" rental_fee="5000000" min_bid="50000000" deposit="1500000">
	<support level="3" lease="7000"/>
	<support level="13" lease="70000"/>
	<support level="5" lease="21000"/>
	<support level="15" lease="210000"/>
	<support level="7" lease="37000"/>
	<support level="17" lease="370000"/>
	<support level="8" lease="52000"/>
	<support level="18" lease="520000"/>
	<item_create level="1" npcId="35463" listId="50045" lease="30000"/>
	<item_create level="2" npcId="35463" listId="50046" lease="70000"/>
	<item_create level="3" npcId="35463" listId="50047" lease="140000"/>
	<curtain level="1" lease="286"/>
	<curtain level="2" lease="375"/>
	<platform level="1" lease="433"/>
	<platform level="2" lease="1333"/>
	<restore_exp level="15" lease="3000"/>
	<restore_exp level="25" lease="9000"/>
	<restore_exp level="35" lease="18000"/>
	<restore_exp level="50" lease="18000"/>
	<restore_hp level="80" lease="1000"/>
	<restore_hp level="120" lease="1500"/>
	<restore_hp level="180" lease="2250"/>
	<restore_hp level="240" lease="3750"/>
	<restore_hp level="300" lease="5166"/>
	<restore_mp level="5" lease="2000"/>
	<restore_mp level="15" lease="6500"/>
	<restore_mp level="30" lease="13750"/>
	<restore_mp level="40" lease="20000"/>
	<teleport level="1" lease="1000">
		<target loc="147728 -56331 -2776" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="147731 -58930 -2976" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
		<target loc="150561 -57489 -2976" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="144866 -57464 -2976" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
	</teleport>
	<teleport level="2" lease="2000">
		<target loc="147728 -56331 -2776" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="147731 -58930 -2976" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
		<target loc="150561 -57489 -2976" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="144866 -57464 -2976" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
		<target loc="125740 -40864 -3736" name="1010491" price="500" StringName="Varka Silenos Stronghold" StringNameLang="Лагерь Фавнов Варка"/><!--Varka Silenos Stronghold-->
		<target loc="146990 -67128 -3640" name="1010492" price="500" StringName="Ketra Orc Outpost" StringNameLang="Застава Орков Кетра"/><!--Ketra Orc Outpost-->
		<target loc="169018 -116303 -2432" name="1010530" price="500" StringName="Entrance to the Forge of the Gods" StringNameLang="Вход в Кузницу Богов"/><!--Entrance to the Forge of the Gods-->
		<target loc="165054 -47861 -3560" name="1010568" price="500" StringName="Wall of Argos" StringNameLang="Стена Аргоса"/><!--Wall of Argos-->
		<target loc="144880 -113468 -2560" name="1010609" price="500" StringName="Hot Springs" StringNameLang="Горячие Источники"/><!--Hot Springs-->
	</teleport>
	<banish_points>
		<point x="147712" y="-58432" z="-2979" />
	</banish_points>
	<owner_restart_points>
		<point x="146960" y="-56768" z="-2765" />
	</owner_restart_points>
	<other_restart_points>
		<point x="147712" y="-58432" z="-2979" />
	</other_restart_points>
	<chaos_restart_points>
	</chaos_restart_points>
</residence>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/residences/[32] the_scarlet_barracks.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="32" name="The Scarlet Barracks" impl="ClanHall" grade="30" rental_fee="5000000" min_bid="8000000" deposit="500000">
	<support level="1" lease="7000"/>
	<support level="11" lease="70000"/>
	<support level="2" lease="11000"/>
	<support level="12" lease="110000"/>
	<support level="4" lease="21000"/>
	<support level="14" lease="210000"/>
	<item_create level="1" npcId="35405" listId="50057" lease="30000"/>
	<item_create level="2" npcId="35405" listId="50058" lease="70000"/>
	<item_create level="3" npcId="35405" listId="50059" lease="140000"/>
	<curtain level="1" lease="286"/>
	<curtain level="2" lease="375"/>
	<platform level="1" lease="433"/>
	<platform level="2" lease="1333"/>
	<restore_exp level="5" lease="3000"/>
	<restore_exp level="15" lease="9000"/>
	<restore_exp level="30" lease="18000"/>
	<restore_hp level="40" lease="800"/>
	<restore_hp level="80" lease="1000"/>
	<restore_hp level="140" lease="1750"/>
	<restore_hp level="160" lease="2000"/>
	<restore_mp level="5" lease="2000"/>
	<restore_mp level="15" lease="6500"/>
	<restore_mp level="25" lease="12000"/>
	<teleport level="1" lease="1000">
		<target loc="19025 145245 -3107" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="21511 145866 -3153" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
		<target loc="18891 142365 -3051" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="17394 147593 -3129" name="1010028" price="0" StringName="South Gate Entrance" StringNameLang="Южные врата"/><!--South Gate Entrance-->
		<target loc="16582 144130 -2960" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
	</teleport>
	<teleport level="2" lease="2000">
		<target loc="19025 145245 -3107" name="1010024" price="0" StringName="Village Square" StringNameLang="Главная площадь"/><!--Village Square-->
		<target loc="21511 145866 -3153" name="1010025" price="0" StringName="North Gate Entrance" StringNameLang="Северные врата"/><!--North Gate Entrance-->
		<target loc="18891 142365 -3051" name="1010026" price="0" StringName="East Gate Entrance" StringNameLang="Восточные врата"/><!--East Gate Entrance-->
		<target loc="17394 147593 -3129" name="1010028" price="0" StringName="South Gate Entrance" StringNameLang="Южные врата"/><!--South Gate Entrance-->
		<target loc="16582 144130 -2960" name="1010027" price="0" StringName="West Gate Entrance" StringNameLang="Западные врата"/><!--West Gate Entrance-->
		<target loc="5106 126916 -3664" name="1010614" price="500" StringName="Cruma Marshlands" StringNameLang="Топи Крумы"/><!--Cruma Marshlands-->
		<target loc="47382 111278 -2104" name="1010113" price="500" StringName="Fortress of Resistance" StringNameLang="Укрепление Партизан"/><!--Fortress of Resistance-->
		<target loc="630 179184 -3720" name="1010111" price="500" StringName="Plains of Dion" StringNameLang="Равнины Диона"/><!--Plains of Dion-->
		<target loc="60374 164301 -2856" name="1010115" price="500" StringName="Tanor Canyon" StringNameLang="Каньон Танор"/><!--Tanor Canyon-->
		<target loc="17430 170103 -3506" name="1010036" price="500" StringName="Entrance to Floran Village" StringNameLang="Деревня Флоран"/><!--Entrance to Floran Village-->
	</teleport>
	<banish_points>
		<point x="18976" y="143360" z="-3033" />
	</banish_points>
	<owner_restart_points>
		<point x="18800" y="143248" z="-3010" />
	</owner_restart_points>
	<other_restart_points>
		<point x="18976" y="143360" z="-3033" />
	</other_restart_points>
	<chaos_restart_points>
	</chaos_restart_points>
</residence>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/residences/[109] borderland_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="109" name="Borderland Fortress" impl="Fortress">
	<support level="7" lease="49000"/>
	<support level="17" lease="490000"/>
	<support level="8" lease="120000"/>
	<support level="18" lease="1200000"/>
	<restore_exp level="45" lease="63000"/>
	<restore_exp level="50" lease="70000"/>
	<restore_hp level="300" lease="12000"/>
	<restore_hp level="400" lease="20000"/>
	<restore_mp level="40" lease="45000"/>
	<restore_mp level="50" lease="65000"/>
	<teleport level="1" lease="1000">
		<target loc="157017 -68977 -2864" name="1010656" price="0" StringName="Fortress West Gate" StringNameLang="Западные врата Крепости"/><!--Fortress West Gate-->
		<target loc="161618 -72057 -2864" name="1010657" price="0" StringName="Fortress East Gate" StringNameLang="Восточные врата Крепости"/><!--Fortress East Gate-->
		<target loc="147728 -56331 -2776" name="1010661" price="0" StringName="Goddard Town Square" StringNameLang="Площадь Годдарда"/><!--Goddard Town Square-->
		<target loc="153996 -50182 -2992" name="1010662" price="0" StringName="Front of the Goddard Castle Gate" StringNameLang="Врата Замка Годдард"/><!--Front of the Goddard Castle Gate-->
	</teleport>
	<teleport level="2" lease="10000">
		<target loc="157017 -68977 -2864" name="1010656" price="0" StringName="Fortress West Gate" StringNameLang="Западные врата Крепости"/><!--Fortress West Gate-->
		<target loc="161618 -72057 -2864" name="1010657" price="0" StringName="Fortress East Gate" StringNameLang="Восточные врата Крепости"/><!--Fortress East Gate-->
		<target loc="147728 -56331 -2776" name="1010661" price="0" StringName="Goddard Town Square" StringNameLang="Площадь Годдарда"/><!--Goddard Town Square-->
		<target loc="153996 -50182 -2992" name="1010662" price="0" StringName="Front of the Goddard Castle Gate" StringNameLang="Врата Замка Годдард"/><!--Front of the Goddard Castle Gate-->
		<target loc="125740 -40864 -3736" name="1010491" price="500" StringName="Varka Silenos Stronghold" StringNameLang="Лагерь Фавнов Варка"/><!--Varka Silenos Stronghold-->
		<target loc="146990 -67128 -3640" name="1010492" price="500" StringName="Ketra Orc Outpost" StringNameLang="Застава Орков Кетра"/><!--Ketra Orc Outpost-->
		<target loc="169018 -116303 -2432" name="1010530" price="500" StringName="Entrance to the Forge of the Gods" StringNameLang="Вход в Кузницу Богов"/><!--Entrance to the Forge of the Gods-->
		<target loc="165054 -47861 -3560" name="1010568" price="500" StringName="Wall of Argos" StringNameLang="Стена Аргоса"/><!--Wall of Argos-->
	</teleport>
	<skills>
		<skill id="591" level="1" /> <!--Residence Spirit-->
		<skill id="610" level="1" /> <!--Residence Death Fortune-->
	</skills>
	<banish_points>
		<point x="153460" y="-70055" z="-3312" />
		<point x="153404" y="-70207" z="-3320" />
		<point x="159400" y="-77923" z="-3672" />
		<point x="159529" y="-77699" z="-3616" />
	</banish_points>
	<owner_restart_points>
		<point x="159361" y="-69939" z="-2536" />
		<point x="159476" y="-70058" z="-2536" />
		<point x="159591" y="-70079" z="-2536" />
	</owner_restart_points>
	<other_restart_points>
		<point x="148560" y="-55904" z="-2779" />
		<point x="150704" y="-55744" z="-2979" />
		<point x="150400" y="-56752" z="-2979" />
		<point x="149872" y="-57424" z="-2979" />
		<point x="149088" y="-56256" z="-2779" />
		<point x="147664" y="-56464" z="-2779" />
		<point x="147680" y="-56928" z="-2779" />
		<point x="146832" y="-55904" z="-2779" />
		<point x="146368" y="-56256" z="-2779" />
		<point x="149120" y="-58064" z="-2979" />
		<point x="148288" y="-58304" z="-2979" />
		<point x="147680" y="-58208" z="-2979" />
		<point x="147232" y="-58480" z="-2979" />
		<point x="146272" y="-58176" z="-2979" />
		<point x="145696" y="-57696" z="-2979" />
		<point x="145264" y="-57680" z="-2979" />
	</other_restart_points>
	<chaos_restart_points>
		<point x="142656" y="-55008" z="-3024" />
		<point x="142832" y="-55680" z="-3462" />
		<point x="143152" y="-56368" z="-3456" />
		<point x="145344" y="-59472" z="-3344" />
		<point x="145872" y="-59744" z="-3328" />
		<point x="150304" y="-59800" z="-3504" />
		<point x="145248" y="-60064" z="-3440" />
		<point x="144368" y="-59616" z="-3512" />
		<point x="149680" y="-59600" z="-3440" />
		<point x="149360" y="-60576" z="-3520" />
		<point x="152114" y="-57296" z="-3451" />
		<point x="150492" y="-59719" z="-3611" />
		<point x="148791" y="-60361" z="-3537" />
		<point x="146499" y="-60242" z="-3455" />
		<point x="143052" y="-56418" z="-3490" />
	</chaos_restart_points>

</residence>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/residences/[110] swamp_fortress.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="110" name="Swamp Fortress" impl="Fortress">
	<support level="7" lease="49000"/>
	<support level="17" lease="490000"/>
	<support level="8" lease="120000"/>
	<support level="18" lease="1200000"/>
	<restore_exp level="45" lease="63000"/>
	<restore_exp level="50" lease="70000"/>
	<restore_hp level="300" lease="12000"/>
	<restore_hp level="400" lease="20000"/>
	<restore_mp level="40" lease="45000"/>
	<restore_mp level="50" lease="65000"/>
	<teleport level="1" lease="1000">
		<target loc="68692 -63928 -2784" name="1010658" price="0" StringName="Fortress North Gate" StringNameLang="Северные врата Крепости"/><!--Fortress North Gate-->
		<target loc="70820 -58862 -2784" name="1010659" price="0" StringName="Fortress South Gate" StringNameLang="Южные врата Крепости"/><!--Fortress South Gate-->
		<target loc="43889 -49101 -792" name="1010671" price="0" StringName="Rune Town Square" StringNameLang="Площадь Руны"/><!--Rune Town Square-->
		<target loc="27400 -49180 -1320" name="1010672" price="0" StringName="Front of the Rune Castle Gate" StringNameLang="Врата Замка Руна"/><!--Front of the Rune Castle Gate-->
	</teleport>
	<teleport level="2" lease="10000">
		<target loc="68692 -63928 -2784" name="1010658" price="0" StringName="Fortress North Gate" StringNameLang="Северные врата Крепости"/><!--Fortress North Gate-->
		<target loc="70820 -58862 -2784" name="1010659" price="0" StringName="Fortress South Gate" StringNameLang="Южные врата Крепости"/><!--Fortress South Gate-->
		<target loc="43889 -49101 -792" name="1010671" price="0" StringName="Rune Town Square" StringNameLang="Площадь Руны"/><!--Rune Town Square-->
		<target loc="27400 -49180 -1320" name="1010672" price="0" StringName="Front of the Rune Castle Gate" StringNameLang="Врата Замка Руна"/><!--Front of the Rune Castle Gate-->
		<target loc="52107 -54328 -3158" name="1010592" price="500" StringName="Forest of the Dead" StringNameLang="Лес Неупокоенных"/><!--Forest of the Dead-->
		<target loc="43805 -88010 -2780" name="1010537" price="500" StringName="Wild Beast Pastures" StringNameLang="Ферма Диких Зверей"/><!--Wild Beast Pastures-->
		<target loc="69340 -50203 -3314" name="1010565" price="500" StringName="Swamp of Screams" StringNameLang="Болото Криков"/><!--Swamp of Screams-->
		<target loc="65307 -71445 -3696" name="1010600" price="500" StringName="Valley of Saints" StringNameLang="Долина Святых"/><!--Valley of Saints-->
		<target loc="76911 -55295 -5824" name="1010706" price="500" StringName="Shyeed's Cavern" StringNameLang="Логово Шиид"/><!--Shyeed's Cavern-->
	</teleport>
	<skills>
		<skill id="597" level="1" /> <!--Residence Shield-->
		<skill id="601" level="1" /> <!--Residence Agility-->
	</skills>
	<banish_points>
		<point x="71814" y="-57054" z="-3088" />
		<point x="71637" y="-57039" z="-3096" />
		<point x="68153" y="-66112" z="-2744" />
		<point x="68039" y="-66247" z="-2736" />
	</banish_points>
	<owner_restart_points>
		<point x="70262" y="-61485" z="-2456" />
		<point x="70283" y="-61645" z="-2456" />
		<point x="70139" y="-61703" z="-2456" />
	</owner_restart_points>
	<other_restart_points>
		<point x="38096" y="-46976" z="899" />
		<point x="38608" y="-47168" z="899" />
		<point x="38752" y="-47792" z="899" />
		<point x="38848" y="-48640" z="899" />
		<point x="38272" y="-49008" z="899" />
		<point x="38112" y="-49792" z="899" />
		<point x="43408" y="-51120" z="-800" />
		<point x="43536" y="-50416" z="-800" />
		<point x="44368" y="-50592" z="-800" />
		<point x="44000" y="-49952" z="-800" />
		<point x="45072" y="-49936" z="-800" />
		<point x="45824" y="-49056" z="-800" />
		<point x="45632" y="-47968" z="-800" />
		<point x="44864" y="-47824" z="-800" />
		<point x="43744" y="-47920" z="-800" />
		<point x="43792" y="-48928" z="-800" />
	</other_restart_points>
	<chaos_restart_points>
		<point x="42640" y="-54496" z="-2310" />
		<point x="38304" y="-55440" z="-1136" />
		<point x="40192" y="-57600" z="-2343" />
		<point x="38400" y="-56832" z="-992" />
		<point x="35632" y="-54800" z="-1744" />
		<point x="36407" y="-54245" z="-1224" />
		<point x="43936" y="-56480" z="-3627" />
		<point x="39440" y="-60080" z="-2870" />
		<point x="41376" y="-55376" z="-1488" />
		<point x="41920" y="-57760" z="-2392" />
		<point x="41409" y="-58699" z="-2848" />
		<point x="40784" y="-59888" z="-2600" />
	</chaos_restart_points>

</residence>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/residences/[1] gludio_castle.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE residence SYSTEM "residence.dtd">
<residence id="1" name="Gludio" impl="Castle">
	<support level="3" lease="7000"/>
	<support level="13" lease="70000"/>
	<support level="5" lease="21000"/>
	<support level="15" lease="210000"/>
	<support level="7" lease="37000"/>
	<support level="17" lease="370000"/>
	<support level="8" lease="52000"/>
	<support level="18" lease="520000"/>
	<restore_exp level="15" lease="3000"/>
	<restore_exp level="25" lease="9000"/>
	<restore_exp level="35" lease="18000"/>
	<restore_exp level="50" lease="18000"/>
	<restore_hp level="80" lease="1000"/>
	<restore_hp level="120" lease="1500"/>
	<restore_hp level="180" lease="2250"/>
	<restore_hp level="240" lease="3750"/>
	<restore_hp level="300" lease="5166"/>
	<restore_mp level="5" lease="2000"/>
	<restore_mp level="15" lease="6500"/>
	<restore_mp level="30" lease="13750"/>
	<restore_mp level="40" lease="20000"/>
	<teleport level="1" lease="1000">
		<target loc="-15043 116596 -3208" name="1010689" price="0" StringName="Front of the Gludio Castle" StringNameLang="Замок Глудио"/><!--Front of the Gludio Castle-->
		<target loc="-14393 123671 -3144" name="1010663" price="0" StringName="Gludio Town Square" StringNameLang="Площадь Глудио"/><!--Gludio Town Square-->
		<target loc="-58761 154663 -2701" name="1010680" price="0" StringName="Front of the Shanty Fortress" StringNameLang="Ветхая Крепость"/><!--Front of the Shanty Fortress-->
		<target loc="-29856 214275 -3680" name="1010667" price="0" StringName="Front of the Southern Fortress" StringNameLang="Южная Крепость"/><!--Front of the Southern Fortress-->
	</teleport>
	<teleport level="2" lease="2000">
		<target loc="-15043 116596 -3208" name="1010689" price="0" StringName="Front of the Gludio Castle" StringNameLang="Замок Глудио"/><!--Front of the Gludio Castle-->
		<target loc="-14393 123671 -3144" name="1010663" price="0" StringName="Gludio Town Square" StringNameLang="Площадь Глудио"/><!--Gludio Town Square-->
		<target loc="-58761 154663 -2701" name="1010680" price="0" StringName="Front of the Shanty Fortress" StringNameLang="Ветхая Крепость"/><!--Front of the Shanty Fortress-->
		<target loc="-29856 214275 -3680" name="1010667" price="0" StringName="Front of the Southern Fortress" StringNameLang="Южная Крепость"/><!--Front of the Southern Fortress-->
		<target loc="-41248 122848 -2912" name="1010097" price="500" StringName="Ruins of Agony" StringNameLang="Руины Страданий"/><!--Ruins of Agony-->
		<target loc="-19120 136816 -3762" name="1010101" price="500" StringName="Ruins of Despair" StringNameLang="Руины Отчаяния"/><!--Ruins of Despair-->
		<target loc="-9959 176184 -4160" name="1010566" price="500" StringName="The Ant Nest" StringNameLang="Муравейник"/><!--The Ant Nest-->
		<target loc="-28327 155125 -3496" name="1010102" price="500" StringName="Windawood Manor" StringNameLang="Поместье Виндавуд"/><!--Windawood Manor-->
	</teleport>
	<skills>
		<skill id="593" level="1" /> <!--Residence Health-->
		<skill id="600" level="1" /> <!--Residence Guidance-->
		<skill id="606" level="1" /> <!--Residence Fortitude-->
	</skills>
	<banish_points>
		<point x="-15881" y="110651" z="-2770" />
		<point x="-15679" y="110168" z="-2770" />
		<point x="-15553" y="110780" z="-2770" />
		<point x="-15281" y="110142" z="-2770" />
	</banish_points>
	<owner_restart_points>
		<point x="-16554" y="109382" z="-1799" />
		<point x="-16869" y="109375" z="-1799" />
		<point x="-16659" y="109261" z="-1799" />
		<point x="-16618" y="109485" z="-1799" />
	</owner_restart_points>
	<other_restart_points>
		<point x="-81447" y="152760" z="-3170" />
		<point x="-81447" y="152880" z="-3170" />
		<point x="-81447" y="152640" z="-3170" />
		<point x="-82186" y="152760" z="-3170" />
		<point x="-82186" y="152880" z="-3170" />
		<point x="-82186" y="152640" z="-3170" />
		<point x="-81780" y="152760" z="-3170" />
		<point x="-81780" y="152880" z="-3170" />
		<point x="-81780" y="152640" z="-3170" />
	</other_restart_points>
	<chaos_restart_points>
		<point x="-81616" y="157104" z="-3150" />
		<point x="-80688" y="157216" z="-3150" />
		<point x="-79568" y="156960" z="-3150" />
		<point x="-78800" y="157744" z="-3150" />
		<point x="-80448" y="157968" z="-3130" />
		<point x="-81712" y="159536" z="-3230" />
		<point x="-79744" y="160592" z="-3330" />
		<point x="-79584" y="159408" z="-3180" />
		<point x="-74016" y="150656" z="-2800" />
		<point x="-72720" y="149632" z="-2780" />
		<point x="-75904" y="162000" z="-3300" />
		<point x="-75488" y="161472" z="-3250" />
		<point x="-74688" y="160736" z="-3200" />
		<point x="-74352" y="161488" z="-3250" />
		<point x="-76656" y="160768" z="-3280" />
		<point x="-77472" y="160960" z="-3470" />
		<point x="-77776" y="158752" z="-3270" />
		<point x="-80448" y="161488" z="-3420" />
		<point x="-75440" y="162672" z="-3350" />
		<point x="-81760" y="161248" z="-3200" />
	</chaos_restart_points>
	<related_fortresses>
		<domain fortress="101" /> <!--Shanty Fortress-->
		<domain fortress="102" />   <!--Southern Fortress-->
		<boundary fortress="112" /> <!--Floran Fortress-->
		<boundary fortress="113" />  <!--Cloud Mountain Fortress-->
	</related_fortresses>
	<merchant_guards>
		<merchant_guard item_id="6038" npc_id="35030" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="6039" npc_id="35031" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="6040" npc_id="35032" ssq="cabal_null;cabal_dawn;" max="5" />
		<merchant_guard item_id="6041" npc_id="35033" ssq="cabal_null;cabal_dawn;" max="1" />
		<merchant_guard item_id="6042" npc_id="35034" ssq="cabal_null;cabal_dawn;" max="1" />
		<merchant_guard item_id="6043" npc_id="35035" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="6044" npc_id="35036" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="6045" npc_id="35037" ssq="cabal_null;cabal_dawn;" max="5" />
		<merchant_guard item_id="6046" npc_id="35038" ssq="cabal_null;cabal_dawn;" max="1" />
		<merchant_guard item_id="6047" npc_id="35039" ssq="cabal_null;cabal_dawn;" max="1" />
		<merchant_guard item_id="6115" npc_id="35020" ssq="cabal_dawn;" max="5" />
		<merchant_guard item_id="6116" npc_id="35021" ssq="cabal_dawn;" max="2" />
		<merchant_guard item_id="6117" npc_id="35022" ssq="cabal_dawn;" max="10" />
		<merchant_guard item_id="6118" npc_id="35023" ssq="cabal_dawn;" max="2" />
		<merchant_guard item_id="6119" npc_id="35024" ssq="cabal_dawn;" max="2" />
		<merchant_guard item_id="6120" npc_id="35025" ssq="cabal_dawn;" max="5" />
		<merchant_guard item_id="6121" npc_id="35026" ssq="cabal_dawn;" max="2" />
		<merchant_guard item_id="6122" npc_id="35027" ssq="cabal_dawn;" max="10" />
		<merchant_guard item_id="6123" npc_id="35028" ssq="cabal_dawn;" max="2" />
		<merchant_guard item_id="6124" npc_id="35029" ssq="cabal_dawn;" max="2" />
		<merchant_guard item_id="6175" npc_id="35040" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6176" npc_id="35041" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6177" npc_id="35042" ssq="cabal_dusk;" max="5" />
		<merchant_guard item_id="6178" npc_id="35043" ssq="cabal_dusk;" max="1" />
		<merchant_guard item_id="6179" npc_id="35044" ssq="cabal_dusk;" max="1" />
		<merchant_guard item_id="6180" npc_id="35045" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6181" npc_id="35046" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6182" npc_id="35047" ssq="cabal_dusk;" max="5" />
		<merchant_guard item_id="6183" npc_id="35048" ssq="cabal_dusk;" max="1" />
		<merchant_guard item_id="6184" npc_id="35049" ssq="cabal_dusk;" max="1" />
		<merchant_guard item_id="6235" npc_id="35050" ssq="cabal_dusk;" max="5" />
		<merchant_guard item_id="6236" npc_id="35051" ssq="cabal_dusk;" max="3" />
		<merchant_guard item_id="6237" npc_id="35052" ssq="cabal_dusk;" max="10" />
		<merchant_guard item_id="6238" npc_id="35053" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6239" npc_id="35054" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6240" npc_id="35055" ssq="cabal_dusk;" max="5" />
		<merchant_guard item_id="6241" npc_id="35056" ssq="cabal_dusk;" max="3" />
		<merchant_guard item_id="6242" npc_id="35057" ssq="cabal_dusk;" max="10" />
		<merchant_guard item_id="6243" npc_id="35058" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6244" npc_id="35059" ssq="cabal_dusk;" max="2" />
		<merchant_guard item_id="6295" npc_id="35060" ssq="cabal_dawn;" max="1" />
		<merchant_guard item_id="6296" npc_id="35061" ssq="cabal_dawn;" max="1" />
		<merchant_guard item_id="3960" npc_id="35010" ssq="cabal_null;cabal_dawn;" max="5" />
		<merchant_guard item_id="3961" npc_id="35011" ssq="cabal_null;cabal_dawn;" max="3" />
		<merchant_guard item_id="3962" npc_id="35012" ssq="cabal_null;cabal_dawn;" max="10" />
		<merchant_guard item_id="3963" npc_id="35013" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="3964" npc_id="35014" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="3965" npc_id="35015" ssq="cabal_null;cabal_dawn;" max="5" />
		<merchant_guard item_id="3966" npc_id="35016" ssq="cabal_null;cabal_dawn;" max="3" />
		<merchant_guard item_id="3967" npc_id="35017" ssq="cabal_null;cabal_dawn;" max="10" />
		<merchant_guard item_id="3968" npc_id="35018" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="3969" npc_id="35019" ssq="cabal_null;cabal_dawn;" max="2" />
		<merchant_guard item_id="3970" npc_id="35092" ssq="cabal_null;cabal_dawn;cabal_dusk;" max="1" />
		<merchant_guard item_id="3971" npc_id="35093" ssq="cabal_null;cabal_dawn;cabal_dusk;" max="1" />
		<merchant_guard item_id="3972" npc_id="35094" ssq="cabal_null;cabal_dawn;cabal_dusk;" max="1" />
	</merchant_guards>
</residence>
