=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/spawn/spawn.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (spawn|territory)*>
<!ELEMENT spawn (territory|npc|point)*>
<!ATTLIST spawn
	group CDATA #IMPLIED
	respawn CDATA #IMPLIED
	count CDATA #IMPLIED
	respawn_random CDATA #IMPLIED
	period_of_day CDATA #IMPLIED>
<!ELEMENT territory (banned_territory|add)*>
<!ATTLIST territory
	name CDATA #IMPLIED>
<!ELEMENT banned_territory (add)*>
<!ELEMENT add (#PCDATA)>
<!ATTLIST add
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	zmin CDATA #REQUIRED
	zmax CDATA #REQUIRED>
<!ELEMENT npc (set)*>
<!ATTLIST npc
	id CDATA #REQUIRED
	max CDATA #IMPLIED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/spawn/16_21.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<territory>
			<add x="-101237" y="103989" zmin="-3692" zmax="-2992"/>
			<add x="-99708" y="100418" zmin="-3692" zmax="-2992"/>
			<add x="-98553" y="100158" zmin="-3692" zmax="-2992"/>
			<add x="-98637" y="104050" zmin="-3692" zmax="-2992"/>
		</territory>
		<npc id="20495"/><!--Turek Orc Warlord-->
	</spawn>
	<spawn count="2" respawn="60" respawn_random="0" period_of_day="none">
		<territory>
			<add x="-101237" y="103989" zmin="-3692" zmax="-2992"/>
			<add x="-99708" y="100418" zmin="-3692" zmax="-2992"/>
			<add x="-98553" y="100158" zmin="-3692" zmax="-2992"/>
			<add x="-98637" y="104050" zmin="-3692" zmax="-2992"/>
		</territory>
		<npc id="20497"/><!--Turek Orc Skirmisher-->
	</spawn>
	<spawn count="2" respawn="60" respawn_random="0" period_of_day="none">
		<territory>
			<add x="-100571" y="106885" zmin="-3715" zmax="-3015"/>
			<add x="-100403" y="104743" zmin="-3715" zmax="-3015"/>
			<add x="-98598" y="104208" zmin="-3715" zmax="-3015"/>
			<add x="-98544" y="109423" zmin="-3715" zmax="-3015"/>
		</territory>
		<npc id="20497"/><!--Turek Orc Skirmisher-->
	</spawn>
	<spawn count="2" respawn="60" respawn_random="0" period_of_day="none">
		<territory>
			<add x="-101237" y="103989" zmin="-3692" zmax="-2992"/>
			<add x="-99708" y="100418" zmin="-3692" zmax="-2992"/>
			<add x="-98553" y="100158" zmin="-3692" zmax="-2992"/>
			<add x="-98637" y="104050" zmin="-3692" zmax="-2992"/>
		</territory>
		<npc id="20498"/><!--Turek Orc Supplier-->
	</spawn>
	<spawn count="2" respawn="60" respawn_random="0" period_of_day="none">
		<territory>
			<add x="-100571" y="106885" zmin="-3715" zmax="-3015"/>
			<add x="-100403" y="104743" zmin="-3715" zmax="-3015"/>
			<add x="-98598" y="104208" zmin="-3715" zmax="-3015"/>
			<add x="-98544" y="109423" zmin="-3715" zmax="-3015"/>
		</territory>
		<npc id="20498"/><!--Turek Orc Supplier-->
	</spawn>
	<spawn count="1" respawn="60" respawn_random="0" period_of_day="none">
		<territory>
			<add x="-101237" y="103989" zmin="-3692" zmax="-2992"/>
			<add x="-99708" y="100418" zmin="-3692" zmax="-2992"/>
			<add x="-98553" y="100158" zmin="-3692" zmax="-2992"/>
			<add x="-98637" y="104050" zmin="-3692" zmax="-2992"/>
		</territory>
		<npc id="20501"/><!--Turek Orc Shaman-->
	</spawn>
	<spawn count="2" respawn="60" respawn_random="0" period_of_day="none">
		<territory>
			<add x="-100571" y="106885" zmin="-3715" zmax="-3015"/>
			<add x="-100403" y="104743" zmin="-3715" zmax="-3015"/>
			<add x="-98598" y="104208" zmin="-3715" zmax="-3015"/>
			<add x="-98544" y="109423" zmin="-3715" zmax="-3015"/>
		</territory>
		<npc id="20501"/><!--Turek Orc Shaman-->
	</spawn>
</list>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/spawn/13_17.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "spawn.dtd">
<list>
	<spawn count="1" respawn="86400" respawn_random="21600" period_of_day="none">
		<point x="-213004" y="175631" z="-11978" h="16380"/>
		<npc id="25698"/><!--Dopagen-->
	</spawn>
	<spawn count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-213003" y="175497" z="-11952" h="16562"/>
		<npc id="18844"/><!--Reptilikon's Ward-->
	</spawn>
	<spawn count="1" respawn="0" respawn_random="0" period_of_day="none">
		<point x="-213003" y="176830" z="-12280" h="48776"/>
		<npc id="18844"/><!--Reptilikon's Ward-->
	</spawn>
</list>
