=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/donation/donation.dtd
<!ELEMENT list (donation)*>
<!ELEMENT donation (simples|foundations|enchant|attribution)*>
	<!ATTLIST donation
		id CDATA #REQUIRED
		name CDATA #REQUIRED
		icon CDATA #REQUIRED
		group CDATA #REQUIRED
		found CDATA #REQUIRED>
		
<!ELEMENT simples (simple)*>
	<!ATTLIST simples
		cost_id CDATA #REQUIRED
		cost_count CDATA #REQUIRED>

<!ELEMENT simple (#PCDATA)*>
	<!ATTLIST simple
		id CDATA #REQUIRED
		count CDATA #REQUIRED
		enchant CDATA #REQUIRED>

<!ELEMENT foundations (foundation)*>
	<!ATTLIST foundations
		cost_id CDATA #REQUIRED
		cost_count CDATA #REQUIRED>

<!ELEMENT foundation (#PCDATA)*>
	<!ATTLIST foundation
		id CDATA #REQUIRED
		count CDATA #REQUIRED
		enchant CDATA #REQUIRED>

<!ELEMENT enchant (#PCDATA)*>
	 <!ATTLIST enchant
		cost_id CDATA #REQUIRED
		cost_count CDATA #REQUIRED
		value CDATA #REQUIRED>

<!ELEMENT attribution (#PCDATA)*>
	 <!ATTLIST attribution
		cost_id CDATA #REQUIRED
		cost_count CDATA #REQUIRED
		value CDATA #REQUIRED
		size CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/donation/donation.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "donation.dtd">
<list>
	<!--
	Group:
		1: Dynasty Armor Set
		2: Moirai Armor Set
		3: Vesper Armor Set
		4: Vorpal Armor Set
		5: Jewels Moirai Set
		6: Icarus Weapon + SA
		7: Vesper Weapon + SA
		8: Mid S84 Weapon + SA
		9: Elegia Armor Set
		10: Elegia Jewels Set
		11: Top S84 Weapons + SA
		12: Jewels Vesper Set
		13: Jewels Vorpal Set
	-->
	<donation id="1" name="Dynasty Armor Set - Heavy" icon="icon.armor_t91_u_i00" group="1" found="true">
		<simples cost_id="37000" cost_count="150">
			<simple id="9422" count="1" enchant="4"/>
			<simple id="9416" count="1" enchant="4"/>
			<simple id="9421" count="1" enchant="4"/>
			<simple id="9423" count="1" enchant="4"/>
			<simple id="9424" count="1" enchant="4"/>
			<simple id="9441" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="11557" count="1" enchant="4"/>
			<foundation id="9416" count="1" enchant="4"/>
			<foundation id="11512" count="1" enchant="4"/>
			<foundation id="11513" count="1" enchant="4"/>
			<foundation id="11526" count="1" enchant="4"/>
			<foundation id="11532" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="100" value="6"/>
	</donation>
	<donation id="2" name="Dynasty Armor Set - Leather" icon="icon.armor_t92_u_i00" group="1" found="true">
		<simples cost_id="37000" cost_count="150">
			<simple id="9429" count="1" enchant="4"/>
			<simple id="9425" count="1" enchant="4"/>
			<simple id="9428" count="1" enchant="4"/>
			<simple id="9430" count="1" enchant="4"/>
			<simple id="9431" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="11525" count="1" enchant="4"/>
			<foundation id="9425" count="1" enchant="4"/>
			<foundation id="11516" count="1" enchant="4"/>
			<foundation id="11515" count="1" enchant="4"/>
			<foundation id="11524" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="100" value="6"/>
	</donation>
	<donation id="3" name="Dynasty Armor Set - Robe" icon="icon.armor_t93_u_i00" group="1" found="true">
		<simples cost_id="37000" cost_count="150">
			<simple id="9438" count="1" enchant="4"/>
			<simple id="9432" count="1" enchant="4"/>
			<simple id="9437" count="1" enchant="4"/>
			<simple id="9439" count="1" enchant="4"/>
			<simple id="9440" count="1" enchant="4"/>
			<simple id="12812" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="11539" count="1" enchant="4"/>
			<foundation id="9432" count="1" enchant="4"/>
			<foundation id="11558" count="1" enchant="4"/>
			<foundation id="11514" count="1" enchant="4"/>
			<foundation id="11533" count="1" enchant="4"/>
			<foundation id="10119" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="100" value="6"/>
	</donation>
	<donation id="4" name="Moirai Armor Set - Heavy" icon="icon.armor_t100_u_i00" group="2" found="true">
		<simples cost_id="37000" cost_count="200">
			<simple id="15606" count="1" enchant="4"/>
			<simple id="15609" count="1" enchant="4"/>
			<simple id="15612" count="1" enchant="4"/>
			<simple id="15615" count="1" enchant="4"/>
			<simple id="15618" count="1" enchant="4"/>
			<simple id="15621" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="16289" count="1" enchant="4"/>
			<foundation id="15609" count="1" enchant="4"/>
			<foundation id="16295" count="1" enchant="4"/>
			<foundation id="16298" count="1" enchant="4"/>
			<foundation id="16301" count="1" enchant="4"/>
			<foundation id="16304" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="100" value="6"/>
	</donation>
	<donation id="5" name="Moirai Armor Set - Leather" icon="icon.armor_t101_u_i00" group="2" found="true">
		<simples cost_id="37000" cost_count="200">
			<simple id="15607" count="1" enchant="4"/>
			<simple id="15610" count="1" enchant="4"/>
			<simple id="15613" count="1" enchant="4"/>
			<simple id="15616" count="1" enchant="4"/>
			<simple id="15619" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="16290" count="1" enchant="4"/>
			<foundation id="15610" count="1" enchant="4"/>
			<foundation id="16296" count="1" enchant="4"/>
			<foundation id="16299" count="1" enchant="4"/>
			<foundation id="16302" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="100" value="6"/>
	</donation>
	<donation id="6" name="Moirai Armor Set - Robe" icon="icon.armor_t102_u_i00" group="2" found="true">
		<simples cost_id="37000" cost_count="200">
			<simple id="15608" count="1" enchant="4"/>
			<simple id="15611" count="1" enchant="4"/>
			<simple id="15614" count="1" enchant="4"/>
			<simple id="15617" count="1" enchant="4"/>
			<simple id="15620" count="1" enchant="4"/>
			<simple id="15622" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="16291" count="1" enchant="4"/>
			<foundation id="15611" count="1" enchant="4"/>
			<foundation id="16297" count="1" enchant="4"/>
			<foundation id="16300" count="1" enchant="4"/>
			<foundation id="16303" count="1" enchant="4"/>
			<foundation id="16305" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="100" value="6"/>
	</donation>
	<donation id="7" name="Vesper Noble Armor Set - Heavy" icon="icon.armor_t94_u_i01" group="3" found="true">
		<simples cost_id="37000" cost_count="250">
			<simple id="13140" count="1" enchant="4"/>
			<simple id="13435" count="1" enchant="4"/>
			<simple id="13448" count="1" enchant="4"/>
			<simple id="13449" count="1" enchant="4"/>
			<simple id="13450" count="1" enchant="4"/>
			<simple id="13471" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="16837" count="1" enchant="4"/>
			<foundation id="13435" count="1" enchant="4"/>
			<foundation id="16843" count="1" enchant="4"/>
			<foundation id="16846" count="1" enchant="4"/>
			<foundation id="16849" count="1" enchant="4"/>
			<foundation id="16321" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="150" value="6"/>
	</donation>
	<donation id="8" name="Vesper Noble Armor Set - Leather" icon="icon.armor_t95_u_i01" group="3" found="true">
		<simples cost_id="37000" cost_count="250">
			<simple id="13141" count="1" enchant="4"/>
			<simple id="13436" count="1" enchant="4"/>
			<simple id="13451" count="1" enchant="4"/>
			<simple id="13452" count="1" enchant="4"/>
			<simple id="13453" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="16838" count="1" enchant="4"/>
			<foundation id="13436" count="1" enchant="4"/>
			<foundation id="16844" count="1" enchant="4"/>
			<foundation id="16847" count="1" enchant="4"/>
			<foundation id="16850" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="150" value="6"/>
	</donation>
	<donation id="9" name="Vesper Noble Armor Set - Robe" icon="icon.armor_t96_u_i01" group="3" found="true">
		<simples cost_id="37000" cost_count="250">
			<simple id="13142" count="1" enchant="4"/>
			<simple id="13437" count="1" enchant="4"/>
			<simple id="13454" count="1" enchant="4"/>
			<simple id="13455" count="1" enchant="4"/>
			<simple id="13456" count="1" enchant="4"/>
			<simple id="12813" count="1" enchant="4"/>
		</simples>
		<foundations cost_id="37000" cost_count="200">
			<foundation id="16839" count="1" enchant="4"/>
			<foundation id="13437" count="1" enchant="4"/>
			<foundation id="16845" count="1" enchant="4"/>
			<foundation id="16848" count="1" enchant="4"/>
			<foundation id="16851" count="1" enchant="4"/>
			<foundation id="16322" count="1" enchant="4"/>
		</foundations>
		<enchant cost_id="37000" cost_count="150" value="6"/>
	</donation>
	<donation id="10" name="Vorpal Armor Set - Heavy" icon="icon.armor_t94_u_i03" group="4" found="false">
		<simples cost_id="37000" cost_count="400">
			<simple id="15589" count="1" enchant="4"/>
			<simple id="15592" count="1" enchant="4"/>
			<simple id="15595" count="1" enchant="4"/>
			<simple id="15598" count="1" enchant="4"/>
			<simple id="15601" count="1" enchant="4"/>
			<simple id="15604" count="1" enchant="4"/>
		</simples>
		<enchant cost_id="37000" cost_count="150" value="6"/>
	</donation>
	<donation id="11" name="Vorpal Armor Set - Leather" icon="icon.armor_t95_u_i03" group="4" found="false">
		<simples cost_id="37000" cost_count="400">
			<simple id="15590" count="1" enchant="4"/>
			<simple id="15593" count="1" enchant="4"/>
			<simple id="15596" count="1" enchant="4"/>
			<simple id="15599" count="1" enchant="4"/>
			<simple id="15602" count="1" enchant="4"/>
		</simples>
		<enchant cost_id="37000" cost_count="150" value="6"/>
	</donation>
	<donation id="12" name="Vorpal Armor Set - Robe" icon="icon.armor_t96_u_i03" group="4" found="false">
		<simples cost_id="37000" cost_count="400">
			<simple id="15591" count="1" enchant="4"/>
			<simple id="15594" count="1" enchant="4"/>
			<simple id="15597" count="1" enchant="4"/>
			<simple id="15600" count="1" enchant="4"/>
			<simple id="15603" count="1" enchant="4"/>
			<simple id="15605" count="1" enchant="4"/>
		</simples>
		<enchant cost_id="37000" cost_count="150" value="6"/>
	</donation>
	<donation id="13" name="Moirai Jewels Set" icon="icon.accessary_bluelycan_necklace_i00" group="5" found="true">
		<simples cost_id="37000" cost_count="100">
			<simple id="15724" count="1" enchant="4"/>
			<simple id="15724" count="1" enchant="4"/>
			<simple id="15725" count="1" enchant="4"/>
