=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/mapregion/domains.dtd
<!ELEMENT list (domain)*>
<!ELEMENT domain (polygon)*>
<!ATTLIST domain
	id CDATA #REQUIRED
	name CDATA #IMPLIED>
<!ELEMENT polygon (coords)*>
<!ELEMENT coords (#PCDATA)>
<!ATTLIST coords
	loc CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/mapregion/domains.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "domains.dtd">
<list>
  <domain id="1" name="Gludio">
    <polygon>
      <coords loc="-121528 98344 -5036 964"/>
      <coords loc="-98372 98344 -5036 964"/>
      <coords loc="-98340 131032 -5036 964"/>
      <coords loc="-122216 131420 -5036 964"/>
    </polygon>
    <polygon>
      <coords loc="-131056 196736 -5212 788"/>
      <coords loc="-98380 196648 -5212 788"/>
      <coords loc="-98428 229188 -5212 788"/>
      <coords loc="-130988 229224 -5212 788"/>
    </polygon>
    <polygon>
      <coords loc="-131020 229516 -4820 1180"/>
      <coords loc="-98484 229588 -4820 1180"/>
      <coords loc="-98396 262080 -4820 1180"/>
      <coords loc="-131064 261872 -4820 1180"/>
    </polygon>
    <polygon>
      <coords loc="-97868 65836 -4904 1096"/>
      <coords loc="-76324 65972 -4904 1096"/>
      <coords loc="-77528 77712 -4904 1096"/>
      <coords loc="-98100 87216 -4904 1096"/>
    </polygon>
    <polygon>
      <coords loc="-98172 87344 -4832 1168"/>
      <coords loc="-80156 79000 -4832 1168"/>
      <coords loc="-78324 86876 -4832 1168"/>
      <coords loc="-80152 98052 -4832 1168"/>
      <coords loc="-98256 98092 -4832 1168"/>
    </polygon>
    <polygon>
      <coords loc="-78308 87376 -3848 2152"/>
      <coords loc="-70516 89252 -3848 2152"/>
      <coords loc="-65788 93912 -3848 2152"/>
      <coords loc="-65736 98076 -3848 2152"/>
      <coords loc="-80084 98040 -3848 2152"/>
    </polygon>
    <polygon>
      <coords loc="-86388 79308 -3468 -2468"/>
      <coords loc="-82064 78388 -3468 -2468"/>
      <coords loc="-80872 84576 -3468 -2468"/>
      <coords loc="-88852 84796 -3468 -2468"/>
      <coords loc="-88992 82552 -3468 -2468"/>
    </polygon>
    <polygon>
      <coords loc="-98388 98168 -3808 2192"/>
      <coords loc="-65688 98296 -3808 2192"/>
      <coords loc="-65600 131076 -3808 2192"/>
      <coords loc="-98300 131356 -3808 2192"/>
    </polygon>
    <polygon>
      <coords loc="-98272 131164 -5024 2976"/>
      <coords loc="-65828 131248 -5024 2976"/>
      <coords loc="-65764 163676 -5024 2976"/>
      <coords loc="-98732 165048 -5024 2976"/>
    </polygon>
    <polygon>
      <coords loc="-98236 163948 -5004 996"/>
      <coords loc="-65724 163856 -5004 996"/>
      <coords loc="-65880 195756 -5004 996"/>
      <coords loc="-98388 196880 -5004 996"/>
    </polygon>
    <polygon>
      <coords loc="-98320 229472 -5036 964"/>
      <coords loc="-65752 229436 -5036 964"/>
      <coords loc="-65468 261984 -5036 964"/>
      <coords loc="-98200 261776 -5036 964"/>
    </polygon>
    <polygon>
      <coords loc="-65488 93628 -4148 1852"/>
      <coords loc="-33092 89240 -4148 1852"/>
      <coords loc="-32964 98112 -4148 1852"/>
      <coords loc="-65476 98100 -4148 1852"/>
    </polygon>
    <polygon>
      <coords loc="-65484 98340 -3780 2220"/>
      <coords loc="-33068 98676 -3780 2220"/>
      <coords loc="-33020 130852 -3780 2220"/>
      <coords loc="-65528 131016 -3780 2220"/>
    </polygon>
    <polygon>
      <coords loc="-65484 131176 -4172 1828"/>
      <coords loc="-32972 131168 -4172 1828"/>
      <coords loc="-33024 163632 -4172 1828"/>
      <coords loc="-65388 163568 -4172 1828"/>
    </polygon>
    <polygon>
      <coords loc="-65440 163896 -5616 384"/>
      <coords loc="-32844 163852 -5616 384"/>
      <coords loc="-32996 196452 -5616 384"/>
      <coords loc="-65532 196488 -5616 384"/>
    </polygon>
    <polygon>
      <coords loc="-65368 196732 -5280 1120"/>
      <coords loc="-33032 196776 -5280 1120"/>
      <coords loc="-33076 229244 -5280 1120"/>
      <coords loc="-65012 229212 -5280 1120"/>
    </polygon>
    <polygon>
      <coords loc="-5032 72868 -4088 -2088"/>
      <coords loc="-24 79252 -4088 -2088"/>
      <coords loc="108 98528 -4088 -2088"/>
      <coords loc="-21568 98404 -4088 -2088"/>
      <coords loc="-22548 90904 -4088 -2088"/>
      <coords loc="-20236 76952 -4088 -2088"/>
      <coords loc="-12260 70068 -4088 -2088"/>
    </polygon>
    <polygon>
      <coords loc="-22232 77188 -5408 -4408"/>
      <coords loc="-10864 77036 -5408 -4408"/>
      <coords loc="-11192 88548 -5408 -4408"/>
      <coords loc="-21852 88044 -5408 -4408"/>
    </polygon>
    <polygon>
      <coords loc="-32480 98448 -4044 1956"/>
      <coords loc="-192 98440 -4044 1956"/>
      <coords loc="388 131392 -4044 1956"/>
      <coords loc="-32692 130880 -4044 1956"/>
    </polygon>
    <polygon>
      <coords loc="-32744 131188 -3904 2096"/>
      <coords loc="-252 131164 -3904 2096"/>
      <coords loc="-124 163732 -3904 2096"/>
      <coords loc="-32696 163648 -3904 2096"/>
    </polygon>
    <polygon>
      <coords loc="-32644 163916 -4464 1536"/>
      <coords loc="-148 163948 -4464 1536"/>
      <coords loc="132 196496 -4464 1536"/>
      <coords loc="-32716 196364 -4464 1536"/>
    </polygon>
    <polygon>
      <coords loc="-32720 196704 -6988 -988"/>
      <coords loc="-64 196664 -6988 -988"/>
      <coords loc="-216 229148 -6988 -988"/>
      <coords loc="-33140 229576 -6988 -988"/>
    </polygon>
    <polygon>
      <coords loc="33600 229712 -5196 804"/>
      <coords loc="65364 230072 -5196 804"/>
      <coords loc="65324 262096 -5196 804"/>
      <coords loc="31612 262128 -5196 804"/>
    </polygon>
  </domain>
  <domain id="2" name="Dion">
    <polygon>
      <coords loc="-57777 -253194 -10208 -3208"/>
      <coords loc="-40997 -252692 -10208 -3208"/>
      <coords loc="-41305 -237750 -10208 -3208"/>
      <coords loc="-58125 -237445 -10208 -3208"/>
    </polygon>
    <polygon>
      <coords loc="3236 98380 -4268 1732"/>
      <coords loc="31976 98800 -4268 1732"/>
      <coords loc="31880 117524 -4268 1732"/>
      <coords loc="2496 112880 -4268 1732"/>
    </polygon>
    <polygon>
      <coords loc="32082 117581 -3796 2204"/>
      <coords loc="32546 130836 -3796 2204"/>
      <coords loc="9062 131116 -3796 2204"/>
      <coords loc="862 127172 -3796 2204"/>
      <coords loc="2410 113013 -3796 2204"/>
    </polygon>
    <polygon>
      <coords loc="2876 155112 -4228 1772"/>
      <coords loc="5860 131136 -4228 1772"/>
      <coords loc="32588 131428 -4228 1772"/>
      <coords loc="32496 163624 -4228 1772"/>
      <coords loc="5600 163816 -4228 1772"/>
    </polygon>
    <polygon>
      <coords loc="92 164016 -4700 1300"/>
      <coords loc="32620 163960 -4700 1300"/>
      <coords loc="32596 196456 -4700 1300"/>
      <coords loc="-8 196608 -4700 1300"/>
    </polygon>
    <polygon>
      <coords loc="56516 99872 -5788 2012"/>
      <coords loc="62188 111928 -5788 2012"/>
      <coords loc="61972 130772 -5788 2012"/>
      <coords loc="32864 130916 -5788 2012"/>
      <coords loc="32824 98272 -5788 2012"/>
    </polygon>
    <polygon>
      <coords loc="32872 131188 -3876 2124"/>
      <coords loc="65324 131368 -3876 2124"/>
      <coords loc="65280 163608 -3876 2124"/>
      <coords loc="33000 163656 -3876 2124"/>
    </polygon>
  </domain>
  <domain id="3" name="Giran">
    <polygon>
      <coords loc="32884 163952 -5112 1088"/>
      <coords loc="33084 196400 -5112 1088"/>
      <coords loc="65244 194620 -5112 1088"/>
      <coords loc="65324 163764 -5112 1088"/>
    </polygon>
    <polygon>
      <coords loc="65740 98480 -4496 1504"/>
      <coords loc="97976 98536 -4496 1504"/>
      <coords loc="97900 130712 -4496 1504"/>
      <coords loc="65604 130920 -4496 1504"/>
    </polygon>
    <polygon>
      <coords loc="65668 131208 -4468 1532"/>
      <coords loc="98012 131164 -4468 1532"/>
      <coords loc="80700 163712 -4468 1532"/>
      <coords loc="65716 163616 -4468 1532"/>
    </polygon>
    <polygon>
      <coords loc="83796 157680 -4632 1368"/>
      <coords loc="98044 131208 -4632 1368"/>
      <coords loc="98212 154536 -4632 1368"/>
    </polygon>
    <polygon>
      <coords loc="65896 163996 -4500 -1500"/>
      <coords loc="80060 164232 -4500 -1500"/>
      <coords loc="70212 180176 -4500 -1500"/>
      <coords loc="65880 184172 -4500 -1500"/>
    </polygon>
    <polygon>
      <coords loc="98544 98724 -4236 1764"/>
      <coords loc="130904 98396 -4236 1764"/>
      <coords loc="130624 130740 -4236 1764"/>
      <coords loc="98384 130748 -4236 1764"/>
    </polygon>
    <polygon>
      <coords loc="130912 131104 -4952 1048"/>
      <coords loc="130976 138376 -4952 1048"/>
      <coords loc="118944 150588 -4952 1048"/>
      <coords loc="98332 153328 -4952 1048"/>
      <coords loc="98412 131148 -4952 1048"/>
    </polygon>
    <polygon>
      <coords loc="33479 197223 -4768 -568"/>
      <coords loc="65148 197187 -4768 -568"/>
      <coords loc="64952 228627 -4768 -568"/>
      <coords loc="33478 228629 -4768 -568"/>
    </polygon>
    <polygon>
      <coords loc="131379 98612 -9187 -687"/>
      <coords loc="163514 98612 -9187 -687"/>
      <coords loc="163514 130860 -9187 -687"/>
      <coords loc="128820 130972 -9187 -687"/>
    </polygon>
  </domain>
  <domain id="4" name="Oren">
    <polygon>
      <coords loc="-74709 66788 -4507 493"/>
      <coords loc="-64139 68684 -4507 493"/>
      <coords loc="-63819 78993 -4507 493"/>
      <coords loc="-77276 77514 -4507 493"/>
    </polygon>
    <polygon>
      <coords loc="-77466 77648 -3611 389"/>
      <coords loc="-64154 79077 -3611 389"/>
      <coords loc="-64722 93562 -3611 389"/>
      <coords loc="-77571 86723 -3611 389"/>
      <coords loc="-79893 79185 -3611 389"/>
    </polygon>
    <polygon>
      <coords loc="-64361 32992 -4708 -708"/>
      <coords loc="-32575 33002 -4708 -708"/>
      <coords loc="-32889 65436 -4708 -708"/>
      <coords loc="-64348 65380 -4708 -708"/>
    </polygon>
    <polygon>
      <coords loc="-65494 65591 -4822 178"/>
      <coords loc="-32918 65544 -4822 178"/>
      <coords loc="-32918 86639 -4822 178"/>
      <coords loc="-65420 93116 -4822 178"/>
    </polygon>
    <polygon>
      <coords loc="-50272 84060 -3612 1388"/>
      <coords loc="-39573 83914 -3612 1388"/>
