=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/zone/zone.dtd
<!ELEMENT list (zone)*>
<!ELEMENT zone (polygon|circle|rectangle|banned_polygon|set|restart_point|PKrestart_point)*>
<!ATTLIST zone
	name CDATA #REQUIRED
	type CDATA #REQUIRED>
<!ELEMENT polygon (coords)*>
<!ELEMENT circle (coords)*>
<!ELEMENT rectangle (coords)*>
<!ELEMENT restart_point (coords)*>
<!ELEMENT PKrestart_point (coords)*>
<!ELEMENT banned_polygon (coords)*>
<!ELEMENT coords (#PCDATA)>
<!ATTLIST coords
	loc CDATA #REQUIRED>
<!ATTLIST circle
	loc CDATA #IMPLIED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	val CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/zone/swamp.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "zone.dtd">
<list>
	<zone name="[spore_boss_swamp_zone]" type="swamp">
		<polygon>
			<coords loc="43084 15944 -4468 -4118"/>
			<coords loc="45140 15816 -4468 -4118"/>
			<coords loc="45748 17200 -4468 -4118"/>
			<coords loc="44504 18780 -4468 -4118"/>
			<coords loc="43284 18952 -4468 -4118"/>
			<coords loc="42476 18164 -4468 -4118"/>
			<coords loc="42480 16448 -4468 -4118"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_8]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418008"/>
		<polygon>
			<coords loc="149084 7070 -560 -360"/>
			<coords loc="149349 7069 -560 -360"/>
			<coords loc="149349 7203 -560 -360"/>
			<coords loc="149084 7204 -560 -360"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_7]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418007"/>
		<polygon>
			<coords loc="149084 6942 -528 -328"/>
			<coords loc="149349 6941 -528 -328"/>
			<coords loc="149349 7075 -528 -328"/>
			<coords loc="149084 7076 -528 -328"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_6]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418006"/>
		<polygon>
			<coords loc="149084 6814 -528 -328"/>
			<coords loc="149349 6813 -528 -328"/>
			<coords loc="149349 6947 -528 -328"/>
			<coords loc="149084 6948 -528 -328"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_5]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418005"/>
		<polygon>
			<coords loc="149084 6686 -528 -328"/>
			<coords loc="149349 6685 -528 -328"/>
			<coords loc="149349 6819 -528 -328"/>
			<coords loc="149084 6820 -528 -328"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_4]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418004"/>
		<polygon>
			<coords loc="145548 7054 -528 -328"/>
			<coords loc="145813 7053 -528 -328"/>
			<coords loc="145813 7187 -528 -328"/>
			<coords loc="145548 7188 -528 -328"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_3]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418003"/>
		<polygon>
			<coords loc="145548 6926 -496 -296"/>
			<coords loc="145813 6925 -496 -296"/>
			<coords loc="145813 7059 -496 -296"/>
			<coords loc="145548 7060 -496 -296"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_2]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418002"/>
		<polygon>
			<coords loc="145548 6798 -496 -296"/>
			<coords loc="145813 6797 -496 -296"/>
			<coords loc="145813 6931 -496 -296"/>
			<coords loc="145548 6932 -496 -296"/>
		</polygon>
	</zone>
	<zone name="[aden_slow_1]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2418001"/>
		<polygon>
			<coords loc="145548 6670 -496 -296"/>
			<coords loc="145813 6669 -496 -296"/>
			<coords loc="145813 6803 -496 -296"/>
			<coords loc="145548 6804 -496 -296"/>
		</polygon>
	</zone>
	<zone name="[gludio_slow_1]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="1921001"/>
		<polygon>
			<coords loc="-18255 110790 -2627 -2427"/>
			<coords loc="-17971 110790 -2627 -2427"/>
			<coords loc="-17972 111174 -2627 -2427"/>
			<coords loc="-18256 111174 -2627 -2427"/>
		</polygon>
	</zone>
	<zone name="[gludio_slow_2]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="1921002"/>
		<polygon>
			<coords loc="-19213 107137 -2595 -2395"/>
			<coords loc="-18827 107137 -2595 -2395"/>
			<coords loc="-18827 107404 -2595 -2395"/>
			<coords loc="-19213 107404 -2595 -2395"/>
		</polygon>
	</zone>
	<zone name="[dion_slow_1]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2022001"/>
		<polygon>
			<coords loc="22215 158960 -2821 30341"/>
			<coords loc="21931 158960 -2821 30341"/>
			<coords loc="21932 158576 -2821 30341"/>
			<coords loc="22216 158576 -2821 30341"/>
		</polygon>
	</zone>
	<zone name="[dion_slow_2]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2022002"/>
		<polygon>
			<coords loc="23173 162613 -2789 30373"/>
			<coords loc="22787 162613 -2789 30373"/>
			<coords loc="22787 162346 -2789 30373"/>
			<coords loc="23173 162346 -2789 30373"/>
		</polygon>
	</zone>
	<zone name="[giran_slow_1]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2322001"/>
		<polygon>
			<coords loc="115132 144954 -2694 13957"/>
			<coords loc="115132 145238 -2694 13957"/>
			<coords loc="114748 145237 -2694 13957"/>
			<coords loc="114748 144953 -2694 13957"/>
		</polygon>
	</zone>
	<zone name="[giran_slow_2]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2322002"/>
		<polygon>
			<coords loc="118785 143996 -2662 13989"/>
			<coords loc="118785 144382 -2662 13989"/>
			<coords loc="118518 144382 -2662 13989"/>
			<coords loc="118518 143996 -2662 13989"/>
		</polygon>
	</zone>
	<zone name="[oren_slow_1]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2219001"/>
		<polygon>
			<coords loc="81208 37049 -2421 13957"/>
			<coords loc="81208 37333 -2421 13957"/>
			<coords loc="80824 37332 -2421 13957"/>
			<coords loc="80824 37048 -2421 13957"/>
		</polygon>
	</zone>
	<zone name="[oren_slow_2]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2219002"/>
		<polygon>
			<coords loc="84861 36091 -2389 13989"/>
			<coords loc="84861 36477 -2389 13989"/>
			<coords loc="84594 36477 -2389 13989"/>
			<coords loc="84594 36091 -2389 13989"/>
		</polygon>
	</zone>
	<zone name="[innadrile_slow_1]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2325001"/>
		<polygon>
			<coords loc="116166 247739 -917 30341"/>
			<coords loc="115882 247739 -917 30341"/>
			<coords loc="115883 247355 -917 30341"/>
			<coords loc="116167 247355 -917 30341"/>
		</polygon>
	</zone>
	<zone name="[innadrile_slow_2]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2325002"/>
		<polygon>
			<coords loc="117124 251392 -885 30373"/>
			<coords loc="116738 251392 -885 30373"/>
			<coords loc="116738 251125 -885 30373"/>
			<coords loc="117124 251125 -885 30373"/>
		</polygon>
	</zone>
	<zone name="[godad_slow_1]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2416001"/>
		<polygon>
			<coords loc="149235 -47768 -1789 -1489"/>
			<coords loc="149579 -47608 -1789 -1489"/>
			<coords loc="149515 -47472 -1789 -1489"/>
			<coords loc="149169 -47634 -1789 -1489"/>
		</polygon>
	</zone>
	<zone name="[godad_slow_2]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="move_bonus" val="-80"/>
		<set name="event" val="2416002"/>
		<polygon>
			<coords loc="145352 -47607 -1789 -1439"/>
			<coords loc="145696 -47768 -1789 -1439"/>
			<coords loc="145760 -47633 -1789 -1439"/>
			<coords loc="145415 -47471 -1789 -1439"/>
		</polygon>
	</zone>
	<zone name="[devil_slow_8]" type="swamp">
		<set name="enabled" val="false"/>
		<set name="target" val="pc"/>
		<set name="unit_tick" val="9"/>
		<set name="initial_delay" val="1"/>
		<set name="on_time" val="120"/>
		<set name="off_time" val="5"/>
		<set name="random_time" val="15"/>
		<set name="move_bonus" val="-80"/>
		<polygon>
			<coords loc="55250 210873 -3964 -3364"/>
			<coords loc="55762 211217 -3964 -3364"/>
			<coords loc="55934 212274 -3964 -3364"/>
			<coords loc="55686 212533 -3964 -3364"/>
			<coords loc="54639 212740 -3964 -3364"/>
			<coords loc="54276 212407 -3964 -3364"/>
			<coords loc="54160 211696 -3964 -3364"/>
			<coords loc="54332 211108 -3964 -3364"/>
		</polygon>
	</zone>
</list>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/zone/kasha_negate.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "zone.dtd">
<list>
	<zone name="[kasha1]" type="dummy">
		<polygon>
			<coords loc="70136 -124744 -3300 -3000"/>
			<coords loc="69672 -125224 -3300 -3000"/>
			<coords loc="69800 -126104 -3300 -3000"/>
			<coords loc="70968 -126664 -3300 -3000"/>
			<coords loc="71848 -126168 -3300 -3000"/>
			<coords loc="72056 -125304 -3300 -3000"/>
			<coords loc="71592 -124584 -3300 -3000"/>
		</polygon>
	</zone>
	<zone name="[kasha2]" type="dummy">
		<polygon>
			<coords loc="73336 -122920 -3300 -2900"/>
			<coords loc="74360 -123112 -3300 -2900"/>
			<coords loc="75544 -122280 -3300 -2900"/>
			<coords loc="76072 -121176 -3300 -2900"/>
			<coords loc="74696 -120040 -3300 -2900"/>
			<coords loc="73288 -120376 -3300 -2900"/>
			<coords loc="72376 -121544 -3300 -2900"/>
		</polygon>
	</zone>
	<zone name="[kasha3]" type="dummy">
		<polygon>
			<coords loc="69000 -122712 -3200 -2700"/>
			<coords loc="68168 -123496 -3200 -2700"/>
			<coords loc="66872 -123416 -3200 -2700"/>
			<coords loc="66344 -122520 -3200 -2700"/>
			<coords loc="66664 -121464 -3200 -2700"/>
			<coords loc="67832 -121000 -3200 -2700"/>
			<coords loc="69048 -122040 -3200 -2700"/>
		</polygon>
	</zone>
	<zone name="[kasha4]" type="dummy">
		<polygon>
			<coords loc="69272 -120232 -3000 -2300"/>
			<coords loc="68120 -118424 -3000 -2300"/>
			<coords loc="70936 -117480 -3000 -2300"/>
			<coords loc="71208 -119128 -3000 -2300"/>
			<coords loc="70552 -120008 -3000 -2300"/>
		</polygon>
	</zone>
	<zone name="[kasha5]" type="dummy">
		<polygon>
			<coords loc="73944 -117544 -2500 -2000"/>
			<coords loc="73528 -116744 -2500 -2000"/>
			<coords loc="73768 -116296 -2500 -2000"/>
			<coords loc="74504 -116056 -2500 -2000"/>
			<coords loc="74952 -116360 -2500 -2000"/>
			<coords loc="75160 -116808 -2500 -2000"/>
			<coords loc="75032 -117240 -2500 -2000"/>
			<coords loc="74200 -117736 -2500 -2000"/>
		</polygon>
	</zone>
	<zone name="[kasha6]" type="dummy">
		<polygon>
			<coords loc="75848 -126088 -3400 -3000"/>
			<coords loc="75128 -126360 -3400 -3000"/>
			<coords loc="74888 -127240 -3400 -3000"/>
			<coords loc="75096 -128008 -3400 -3000"/>
			<coords loc="75832 -128584 -3400 -3000"/>
			<coords loc="76472 -128568 -3400 -3000"/>
			<coords loc="77048 -128200 -3400 -3000"/>
			<coords loc="77272 -127192 -3400 -3000"/>
			<coords loc="76808 -126424 -3400 -3000"/>
		</polygon>
	</zone>
	<zone name="[kasha7]" type="dummy">
		<polygon>
			<coords loc="72616 -128616 -3700 -3200"/>
			<coords loc="72248 -129624 -3700 -3200"/>
			<coords loc="71384 -129800 -3700 -3200"/>
			<coords loc="70664 -129336 -3700 -3200"/>
			<coords loc="70584 -128648 -3700 -3200"/>
			<coords loc="71528 -127928 -3700 -3200"/>
			<coords loc="72152 -128264 -3700 -3200"/>
		</polygon>
	</zone>
	<zone name="[kasha8]" type="dummy">
		<polygon>
			<coords loc="69608 -116408 -2400 -1900"/>
			<coords loc="69352 -117224 -2400 -1900"/>
			<coords loc="67928 -117512 -2400 -1900"/>
			<coords loc="67016 -116808 -2400 -1900"/>
			<coords loc="67448 -114776 -2400 -1900"/>
			<coords loc="68456 -114584 -2400 -1900"/>
			<coords loc="69576 -115448 -2400 -1900"/>
		</polygon>
	</zone>
</list>
