=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/option_data/option_data.dtd
<!ELEMENT list (option_data)*>
<!ELEMENT option_data  (for|set|skills|triggers)*>
<!ATTLIST option_data
	id CDATA #REQUIRED>

<!ELEMENT for (add|set|mul)*>
<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>


<!ELEMENT or (player|target|using|zone)*>
<!ELEMENT not (player|target|using|zone)*>
<!ELEMENT and (player|target|using|zone)*>



<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	residence CDATA #IMPLIED
	classId CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	pvp CDATA #REQUIRED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/option_data/7400-7499.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "option_data.dtd">
<list>
	<option_data id="7400">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="pAtk" value="2.313" />
		</for>
	</option_data>
	<option_data id="7401">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="mAtk" value="2.655" />
		</for>
	</option_data>
	<option_data id="7402">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="regHp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7403">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="regMp" value="0.05049" />
		</for>
	</option_data>
	<option_data id="7404">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7405">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7406">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7407">
		<for>
			<add order="0x60" stat="mDef" value="4.54" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7408">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="maxMp" value="6.228" />
		</for>
	</option_data>
	<option_data id="7409">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="maxCp" value="27.522" />
		</for>
	</option_data>
	<option_data id="7410">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="pAtk" value="2.313" />
		</for>
	</option_data>
	<option_data id="7411">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="mAtk" value="2.655" />
		</for>
	</option_data>
	<option_data id="7412">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="regHp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7413">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="regMp" value="0.05049" />
		</for>
	</option_data>
	<option_data id="7414">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7415">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7416">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7417">
		<for>
			<add order="0x60" stat="maxHp" value="22.15" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7418">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="maxCp" value="27.522" />
		</for>
	</option_data>
	<option_data id="7419">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="pAtk" value="2.313" />
		</for>
	</option_data>
	<option_data id="7420">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="mAtk" value="2.655" />
		</for>
	</option_data>
	<option_data id="7421">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="regHp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7422">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="regMp" value="0.05049" />
		</for>
	</option_data>
	<option_data id="7423">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7424">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7425">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7426">
		<for>
			<add order="0x60" stat="maxMp" value="6.92" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7427">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="pAtk" value="2.313" />
		</for>
	</option_data>
	<option_data id="7428">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="mAtk" value="2.655" />
		</for>
	</option_data>
	<option_data id="7429">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="regHp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7430">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="regMp" value="0.05049" />
		</for>
	</option_data>
	<option_data id="7431">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7432">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7433">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7434">
		<for>
			<add order="0x60" stat="maxCp" value="30.58" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7435">
		<for>
			<add order="0x60" stat="pAtk" value="2.57" />
			<add order="0x60" stat="mAtk" value="2.655" />
		</for>
	</option_data>
	<option_data id="7436">
		<for>
			<add order="0x60" stat="pAtk" value="2.57" />
			<add order="0x60" stat="regHp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7437">
		<for>
			<add order="0x60" stat="pAtk" value="2.57" />
			<add order="0x60" stat="regMp" value="0.05049" />
		</for>
	</option_data>
	<option_data id="7438">
		<for>
			<add order="0x60" stat="pAtk" value="2.57" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7439">
		<for>
			<add order="0x60" stat="pAtk" value="2.57" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7440">
		<for>
			<add order="0x60" stat="pAtk" value="2.57" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7441">
		<for>
			<add order="0x60" stat="pAtk" value="2.57" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7442">
		<for>
			<add order="0x60" stat="mAtk" value="2.95" />
			<add order="0x60" stat="regHp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7443">
		<for>
			<add order="0x60" stat="mAtk" value="2.95" />
			<add order="0x60" stat="regMp" value="0.05049" />
		</for>
	</option_data>
	<option_data id="7444">
		<for>
			<add order="0x60" stat="mAtk" value="2.95" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7445">
		<for>
			<add order="0x60" stat="mAtk" value="2.95" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7446">
		<for>
			<add order="0x60" stat="mAtk" value="2.95" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7447">
		<for>
			<add order="0x60" stat="mAtk" value="2.95" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7448">
		<for>
			<add order="0x60" stat="regHp" value="0.1195" />
			<add order="0x60" stat="regMp" value="0.05049" />
		</for>
	</option_data>
	<option_data id="7449">
		<for>
			<add order="0x60" stat="regHp" value="0.1195" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7450">
		<for>
			<add order="0x60" stat="regHp" value="0.1195" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7451">
		<for>
			<add order="0x60" stat="regHp" value="0.1195" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7452">
		<for>
			<add order="0x60" stat="regHp" value="0.1195" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7453">
		<for>
			<add order="0x60" stat="regMp" value="0.0561" />
			<add order="0x60" stat="regCp" value="0.10755" />
		</for>
	</option_data>
	<option_data id="7454">
		<for>
			<add order="0x60" stat="regMp" value="0.0561" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7455">
		<for>
			<add order="0x60" stat="regMp" value="0.0561" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7456">
		<for>
			<add order="0x60" stat="regMp" value="0.0561" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7457">
		<for>
			<add order="0x60" stat="regCp" value="0.1195" />
			<add order="0x60" stat="rEvas" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7458">
		<for>
			<add order="0x60" stat="regCp" value="0.1195" />
			<add order="0x60" stat="accCombat" value="0.492406" />
		</for>
	</option_data>
	<option_data id="7459">
		<for>
			<add order="0x60" stat="regCp" value="0.1195" />
			<add order="0x60" stat="baseCrit" value="5.331772168" />
		</for>
	</option_data>
	<option_data id="7460">
		<for>
			<add order="0x60" stat="rEvas" value="0.544238" />
			<add order="0x60" stat="accCombat" value="0.492406" />
