=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/items/item.dtd
<!ELEMENT list (weapon|etcitem|armor)*>
<!ELEMENT weapon  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options)*>
<!ATTLIST weapon
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT etcitem (set|equip|for|enchant4_skill|cond|skills|triggers|enchant_options|capsuled_items)*>
<!ATTLIST etcitem
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>
<!ELEMENT armor  (set|equip|for|enchant4_skill|cond|skills|triggers|attributes|enchant_options)*>
<!ATTLIST armor
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	add_name CDATA #IMPLIED>

<!ELEMENT enchant_options (level)*>
<!ELEMENT level (option)*>
<!ATTLIST level
	val CDATA #REQUIRED>
<!ELEMENT option (#PCDATA)>
<!ATTLIST option
	id CDATA #REQUIRED>

<!ELEMENT equip (slot)*>
<!ELEMENT slot (#PCDATA)>
<!ATTLIST slot
	id CDATA #REQUIRED>

<!ELEMENT cond (player|target|using|zone|or|not|and)*>
<!ATTLIST cond
	msgId CDATA #IMPLIED
	addName CDATA #IMPLIED>
<!ELEMENT or (player|target|using|zone)*>
<!ELEMENT not (player|target|using|zone)*>
<!ELEMENT and (player|target|using|zone)*>
<!ELEMENT player (#PCDATA)>
<!ATTLIST player
	residence CDATA #IMPLIED
	olympiad CDATA #IMPLIED
	fightClub CDATA #IMPLIED
	race CDATA #IMPLIED
	instance_zone CDATA #IMPLIED
	sex CDATA #IMPLIED
	event CDATA #IMPLIED
	classId CDATA #IMPLIED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	mob_corpse CDATA #IMPLIED
	pvp CDATA #IMPLIED>
<!ELEMENT using (#PCDATA)>
<!ATTLIST using
	slotitem CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	type CDATA #REQUIRED>

<!ELEMENT for (add|set|mul|enchant)*>
<!ELEMENT add (player|target|using|zone|or|not|and)*>
<!ATTLIST add
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT attributes (attribute)*>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute
	element CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT capsuled_items (capsuled_item)*>
<!ELEMENT capsuled_item (#PCDATA)>
<!ATTLIST capsuled_item
	id CDATA #REQUIRED
	min_count CDATA #REQUIRED
	max_count CDATA #REQUIRED
	chance CDATA #REQUIRED>

<!ELEMENT mul (player|target|using|zone)*>
<!ATTLIST mul
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT set (player|target|using|zone|or|not|and)*>
<!ATTLIST set
	name CDATA #IMPLIED
	order CDATA #IMPLIED
	stat CDATA #IMPLIED
	value CDATA #REQUIRED>

<!ELEMENT enchant (#PCDATA)>
<!ATTLIST enchant
	order CDATA #REQUIRED
	stat CDATA #REQUIRED
	value CDATA #REQUIRED>

<!ELEMENT enchant4_skill (#PCDATA)>
<!ATTLIST enchant4_skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>

<!ELEMENT triggers (trigger)*>
<!ELEMENT trigger (#PCDATA)>
<!ATTLIST trigger
	id CDATA #REQUIRED
	level CDATA #REQUIRED
	type CDATA #REQUIRED
	chance CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/items/8400-8499.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE list SYSTEM "item.dtd">

<list>
  <etcitem id="8400" name="Spellbook: Turn Undead">
    <set name="class" value="SPELLBOOKS"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_spell_books_assistance_i00"/>
    <set name="price" value="6250"/>
    <set name="stackable" value="true"/>
    <set name="type" value="SPELLBOOK"/>
    <set name="weight" value="120"/>
  </etcitem>
  <etcitem id="8401" name="Spellbook: Major Heal">
    <set name="class" value="SPELLBOOKS"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_spell_books_assistance_i00"/>
    <set name="price" value="6250"/>
    <set name="stackable" value="true"/>
    <set name="type" value="SPELLBOOK"/>
    <set name="weight" value="120"/>
  </etcitem>
  <etcitem id="8402" name="Spellbook: Major Group Heal">
    <set name="class" value="SPELLBOOKS"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_spell_books_assistance_i00"/>
    <set name="price" value="6750"/>
    <set name="stackable" value="true"/>
    <set name="type" value="SPELLBOOK"/>
    <set name="weight" value="120"/>
  </etcitem>
  <etcitem id="8403" name="Small Nimble Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i07"/>
    <set name="price" value="138"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8404" name="Small Ugly Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i07"/>
    <set name="price" value="141"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8405" name="Small Pudgy Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i07"/>
    <set name="price" value="153"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8406" name="Nimble Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i07"/>
    <set name="price" value="167"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8407" name="Ugly Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i07"/>
    <set name="price" value="187"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8408" name="Pudgy Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i07"/>
    <set name="price" value="208"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8409" name="Large Nimble Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i07"/>
    <set name="price" value="225"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8410" name="Large Ugly Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i07"/>
    <set name="price" value="248"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8411" name="Large Pudgy Green Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i07"/>
    <set name="price" value="265"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8412" name="Small Jade Nimble Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i06"/>
    <set name="price" value="285"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8413" name="Small Jade Ugly Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i06"/>
    <set name="price" value="295"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8414" name="Small Jade Fat Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i06"/>
    <set name="price" value="310"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8415" name="Jade Nimble Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i06"/>
    <set name="price" value="325"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8416" name="Jade Ugly Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i06"/>
    <set name="price" value="340"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8417" name="Jade Fat Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i06"/>
    <set name="price" value="355"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8418" name="Large Jade Nimble Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i06"/>
    <set name="price" value="365"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8419" name="Large Jade Ugly Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i06"/>
    <set name="price" value="375"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8420" name="Large Jade Fat Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i06"/>
    <set name="price" value="385"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8421" name="Small Blue Nimble Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i01"/>
    <set name="price" value="395"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8422" name="Small Blue Ugly Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i01"/>
    <set name="price" value="400"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8423" name="Small Blue Fat Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i01"/>
    <set name="price" value="410"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8424" name="Blue Nimble Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_tuna_i01"/>
    <set name="price" value="415"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8425" name="Blue Ugly Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_angler_i01"/>
    <set name="price" value="418"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8426" name="Blue Fat Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
    <set name="icon" value="icon.etc_bream_i01"/>
    <set name="price" value="420"/>
    <set name="stackable" value="true"/>
    <set name="type" value="OTHER"/>
    <set name="weight" value="100"/>
  </etcitem>
  <etcitem id="8427" name="Large Blue Nimble Fish - Upper Grade">
    <set name="class" value="OTHER"/>
    <set name="crystal_type" value="NONE"/>
