=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/doors/doors.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT list (door)*>
<!ELEMENT door (pos|shape|set|ai_params)*>
<!ATTLIST door
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	hp CDATA #REQUIRED
	hp CDATA #REQUIRED
	pdef CDATA #REQUIRED
	mdef CDATA #REQUIRED
	type CDATA #IMPLIED
	residence_id CDATA #IMPLIED>
<!ELEMENT pos (#PCDATA)>
<!ATTLIST pos
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT shape (#PCDATA)>
<!ELEMENT ai_params (set)*>
<!ATTLIST shape
	ax CDATA #REQUIRED
	ay CDATA #REQUIRED
	bx CDATA #REQUIRED
	by CDATA #REQUIRED
	cx CDATA #REQUIRED
	cy CDATA #REQUIRED
	dx CDATA #REQUIRED
	dy CDATA #REQUIRED
	minz CDATA #REQUIRED
	maxz CDATA #REQUIRED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/doors/23_13.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE list SYSTEM "doors.dtd">

<list>
	<door id="23130001" name="L2fortress_snow_S.fort_wall_door01_snow" hp="474750" pdef="644" mdef="518">
		<pos x="107495" y="-140524" z="-3009"/>
		<shape ax="107513" ay="-140616" bx="107565" by="-140465" cx="107477" cy="-140436" dx="107428" dy="-140591" minz="-3009" maxz="-2859"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="true"/>
		<set name="close_time" value="60"/>
	</door>
	<door id="23130002" name="L2fortress_snow_S.fort_indoorsnw" hp="474750" pdef="644" mdef="518">
		<pos x="108887" y="-141124" z="-2984"/>
		<shape ax="108918" ay="-141051" bx="108894" by="-141126" cx="108879" cy="-141122" dx="108901" dy="-141046" minz="-2984" maxz="-2834"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="false"/>
		<set name="close_time" value="60"/>
	</door>
	<door id="23130003" name="L2fortress_snow_S.fort_indoorsnw" hp="474750" pdef="644" mdef="518">
		<pos x="108932" y="-140975" z="-2984"/>
		<shape ax="108917" ay="-141054" bx="108941" by="-140977" cx="108922" cy="-140971" dx="108900" dy="-141049" minz="-2984" maxz="-2834"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="false"/>
		<set name="close_time" value="60"/>
	</door>
	<door id="23130004" name="L2fortress_snow_S.fort_indoorsnw" hp="474750" pdef="644" mdef="518">
		<pos x="110037" y="-141473" z="-2984"/>
		<shape ax="110069" ay="-141399" bx="110045" by="-141477" cx="110028" cy="-141471" dx="110052" dy="-141394" minz="-2984" maxz="-2834"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="false"/>
		<set name="close_time" value="60"/>
	</door>
	<door id="23130005" name="L2fortress_snow_S.fort_indoorsnw" hp="474750" pdef="644" mdef="518">
		<pos x="110082" y="-141324" z="-2984"/>
		<shape ax="110069" ay="-141402" bx="110093" by="-141326" cx="110073" cy="-141319" dx="110051" dy="-141398" minz="-2984" maxz="-2834"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="false"/>
		<set name="close_time" value="60"/>
	</door>
	<door id="23130006" name="L2fortress_snow_S.fort_wall_door01_snow" hp="474750" pdef="644" mdef="518">
		<pos x="111423" y="-141714" z="-3009"/>
		<shape ax="111441" ay="-141806" bx="111493" by="-141655" cx="111405" cy="-141626" dx="111356" dy="-141781" minz="-3009" maxz="-2859"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="true"/>
		<set name="close_time" value="60"/>
	</door>
	<door id="23130007" name="L2fortress_snow_S.fort_indoorsnw" hp="474750" pdef="644" mdef="518">
		<pos x="110210" y="-140000" z="-2959"/>
		<shape ax="110242" ay="-139926" bx="110218" by="-140004" cx="110201" cy="-139998" dx="110225" dy="-139921" minz="-2959" maxz="-2809"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="true"/>
		<set name="close_time" value="60"/>
		<set name="ai" value="ResidenceDoor"/>
		<ai_params>
			<set name="residence_id" value="111"/>
		</ai_params>
	</door>
	<door id="23130008" name="L2fortress_snow_S.fort_indoorsnw" hp="474750" pdef="644" mdef="518">
		<pos x="110255" y="-139851" z="-2959"/>
		<shape ax="110242" ay="-139929" bx="110266" by="-139853" cx="110246" cy="-139846" dx="110224" dy="-139925" minz="-2959" maxz="-2809"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="true"/>
		<set name="close_time" value="60"/>
		<set name="ai" value="ResidenceDoor"/>
		<ai_params>
			<set name="residence_id" value="111"/>
		</ai_params>
	</door>
</list>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/doors/20_24.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE list SYSTEM "doors.dtd">

<list>
	<door id="20240001" name="bereth_S.bereth_Door01" hp="158250" pdef="644" mdef="518">
		<pos x="16326" y="210714" z="-9399"/>
		<shape ax="16224" ay="210719" bx="16224" by="210708" cx="16427" cy="210708" dx="16427" dy="210720" minz="-9399" maxz="-9249"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="false"/>
	</door>
	<door id="20240002" name="bereth_S.bereth_Door01" hp="158250" pdef="644" mdef="518">
		<pos x="14032" y="213143" z="-9399"/>
		<shape ax="14026" ay="213045" bx="14039" by="213045" cx="14039" cy="213241" dx="14025" dy="213240" minz="-9399" maxz="-9249"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="false"/>
		<set name="close_time" value="600"/>
	</door>
	<door id="20240003" name="bereth_S.bereth_Door01" hp="158250" pdef="644" mdef="518">
		<pos x="12472" y="214696" z="-9384"/>
		<shape ax="12372" ay="214689" bx="12569" by="214688" cx="12570" cy="214702" dx="12372" dy="214703" minz="-9384" maxz="-9234"/>
		<set name="opened" value="false"/>
		<set name="unlockable" value="false"/>
		<set name="key" value="0"/>
		<set name="show_hp" value="false"/>
	</door>
</list>
