=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/events/events.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (event)*>
<!ELEMENT event (parameter|on_start|on_stop|on_init|on_time|objects)*>
<!ATTLIST event
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	name_ru CDATA #IMPLIED
	type CDATA #REQUIRED
	impl CDATA #REQUIRED>
<!ELEMENT parameter (#PCDATA)>
<!ATTLIST parameter
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT on_start  (if|ifnot|else|start|stop|spawn|despawn|npc_say|say|play_sound|open|close|refresh|init|announce|voicedToLeaders|voicedToAll|voicedToParticipants|active|deactive|give_item|teleport_players)*>
<!ELEMENT on_stop   (if|ifnot|else|start|stop|spawn|despawn|npc_say|say|play_sound|open|close|refresh|init|announce|voicedToLeaders|voicedToAll|voicedToParticipants|active|deactive|give_item|teleport_players)*>
<!ELEMENT on_init   (if|ifnot|else|start|stop|spawn|despawn|npc_say|say|play_sound|open|close|refresh|init|announce|voicedToLeaders|voicedToAll|voicedToParticipants|active|deactive|give_item|teleport_players)*>
<!ELEMENT on        (if|ifnot|else|start|stop|spawn|despawn|npc_say|say|play_sound|open|close|refresh|init|announce|voicedToLeaders|voicedToAll|voicedToParticipants|active|deactive|give_item|teleport_players)*>
<!ELEMENT if        (if|ifnot|else|start|stop|spawn|despawn|npc_say|say|play_sound|open|close|refresh|init|announce|voicedToLeaders|voicedToAll|voicedToParticipants|active|deactive|give_item|teleport_players)*>
<!ELEMENT ifnot     (if|ifnot|else|start|stop|spawn|despawn|npc_say|say|play_sound|open|close|refresh|init|announce|voicedToLeaders|voicedToAll|voicedToParticipants|active|deactive|give_item|teleport_players)*>
<!ELEMENT else      (if|ifnot|else|start|stop|spawn|despawn|npc_say|say|play_sound|open|close|refresh|init|announce|voicedToLeaders|voicedToAll|voicedToParticipants|active|deactive|give_item|teleport_players)*>
<!ATTLIST if
	name CDATA #REQUIRED>
<!ATTLIST ifnot
	name CDATA #REQUIRED>
<!ELEMENT on_time (on)*>
<!ATTLIST on
	time CDATA #REQUIRED>
<!ELEMENT start (#PCDATA)>
<!ATTLIST start
	name CDATA #REQUIRED>
<!ELEMENT stop (#PCDATA)>
<!ATTLIST stop
	name CDATA #REQUIRED>
<!ELEMENT spawn (#PCDATA)>
<!ATTLIST spawn
	name CDATA #REQUIRED>
<!ELEMENT open (#PCDATA)>
<!ATTLIST open
	name CDATA #REQUIRED>
<!ELEMENT close (#PCDATA)>
<!ATTLIST close
	name CDATA #REQUIRED>
<!ELEMENT active (#PCDATA)>
<!ATTLIST active
	name CDATA #REQUIRED>
<!ELEMENT deactive (#PCDATA)>
<!ATTLIST deactive
	name CDATA #REQUIRED>
<!ELEMENT refresh (#PCDATA)>
<!ATTLIST refresh
	name CDATA #REQUIRED>
<!ELEMENT init (#PCDATA)>
<!ATTLIST init
	name CDATA #REQUIRED>
<!ELEMENT announce (#PCDATA)>
<!ATTLIST announce
	val CDATA #IMPLIED>
<!ELEMENT voicedToLeaders (#PCDATA)>
<!ATTLIST voicedToLeaders
	bypass CDATA #IMPLIED>
<!ELEMENT voicedToAll (#PCDATA)>
<!ATTLIST voicedToAll
	bypass CDATA #IMPLIED>
<!ELEMENT voicedToParticipants (#PCDATA)>
<!ATTLIST voicedToParticipants
	bypass CDATA #IMPLIED>
<!ELEMENT despawn (#PCDATA)>
<!ATTLIST despawn
	name CDATA #REQUIRED>
<!ELEMENT objects (door|spawn_ex|point|boat_point|static_object|siege_toggle_npc|castle_zone|combat_flag|ctb_team|cmg_arena|territory_ward|zone)*>
<!ATTLIST objects
	name CDATA #REQUIRED>
<!ELEMENT door (#PCDATA)>
<!ATTLIST door
	id CDATA #REQUIRED>
<!ELEMENT siege_toggle_npc (objects)*>
<!ATTLIST siege_toggle_npc
	id CDATA #REQUIRED
	fake_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	hp CDATA #REQUIRED>
<!ELEMENT castle_zone (#PCDATA)>
<!ATTLIST castle_zone
	name CDATA #REQUIRED
	price CDATA #REQUIRED>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	name CDATA #REQUIRED>
<!ELEMENT static_object (#PCDATA)>
<!ATTLIST static_object
	id CDATA #REQUIRED>
<!ELEMENT spawn_ex (#PCDATA)>
<!ATTLIST spawn_ex
	name CDATA #REQUIRED>
<!ELEMENT combat_flag (#PCDATA)>
<!ATTLIST combat_flag
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT territory_ward (#PCDATA)>
<!ATTLIST territory_ward
	item_id CDATA #REQUIRED
	npc_id CDATA #REQUIRED
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED>
<!ELEMENT ctb_team (#PCDATA)>
<!ATTLIST ctb_team
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #REQUIRED
	id CDATA #REQUIRED
	mob_id CDATA #REQUIRED>
<!ELEMENT cmg_arena (#PCDATA)>
<!ELEMENT boat_point (#PCDATA)>
<!ATTLIST boat_point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	speed1 CDATA #REQUIRED
	speed2 CDATA #REQUIRED
	fuel CDATA #IMPLIED
	teleport CDATA #IMPLIED>
<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	x CDATA #REQUIRED
	y CDATA #REQUIRED
	z CDATA #REQUIRED
	h CDATA #IMPLIED>
<!ELEMENT npc_say (add)*>
<!ATTLIST npc_say
	npc CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT add (#PCDATA)*>
<!ATTLIST add
	value CDATA #REQUIRED>
<!ELEMENT teleport_players (#PCDATA)*>
<!ATTLIST teleport_players
	id CDATA #REQUIRED>
<!ELEMENT say (#PCDATA)>
<!ATTLIST say
	how CDATA #REQUIRED
	chat CDATA #REQUIRED
	range CDATA #REQUIRED
	text CDATA #REQUIRED>
<!ELEMENT play_sound (#PCDATA)>
<!ATTLIST play_sound
	type CDATA #REQUIRED
	sound CDATA #REQUIRED
	range CDATA #REQUIRED>
<!ELEMENT give_item (#PCDATA)>
<!ATTLIST give_item
	id CDATA #REQUIRED
	count CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/events/fight_club/[7] Protect_The_King.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "../events.dtd">
<list>
	<event id="7" name="Protect The King" type="FIGHT_CLUB_EVENT" impl="fightclub.ProtectTheKing">
		<parameter name="icon" value="L2UI_CH3.fishskill"/>
		<parameter name="desc" value="Team Event. One of the City Defenders is selected to be the King. If he will get killed, attackers will take control over the City! Team who will be defending the City when Event ends, will claim the Reward!"/>
		<parameter name="roundRunTime" value="600"/>
        <parameter name="roundEvent" value="false"/>
        <parameter name="isAutoTimed" value="true"/>
        <parameter name="autoTimes" value="05:00,13:00,21:00"/>
        <parameter name="teamed" value="true"/>
		<parameter name="buffer" value="true"/>
		<parameter name="fighterBuffs" value="1204,2;1086,2;1068,3;1045,6;1048,6;1040,3;1062,2;1036,2"/>
		<parameter name="mageBuffs" value="1204,2;1085,3;1059,3;1045,6;1048,6;1040,3;1062,2;1036,2"/>
		<parameter name="rootBetweenRounds" value="true"/>
		<parameter name="excludedClasses" value=""/>
		<parameter name="respawnTime" value="5"/>
		<parameter name="respawnTime_DEFENDER" value="15"/>
		<parameter name="ressAllowed" value="false"/>
		<parameter name="showPersonality" value="true"/>
		<parameter name="badgesKillPlayer" value="0"/>
		<parameter name="badgesKillPet" value="0"/>
		<parameter name="badgesDie" value="0"/>
		<parameter name="badgesWin" value="6"/>
		<parameter name="badgesLose" value="2"/>
		<parameter name="topKillerReward" value="3"/>

		<parameter name="waitSecondsAfterKingDeath" value="5"/>
		<parameter name="kingNameColor" value="00fff6"/>
		<parameter name="announceKingName" value="False"/>
	</event>
</list>
