=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/fight_club_maps/maps.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (map)*>
<!ELEMENT map (parameter|objects)*>
<!ATTLIST map
		name CDATA #REQUIRED>

		<!ELEMENT parameter (#PCDATA)>
		<!ATTLIST parameter
				name CDATA #REQUIRED
				value CDATA #REQUIRED>
		<!ELEMENT objects (door|point|zone|npcLoc)*>
		<!ATTLIST objects
				name CDATA #REQUIRED
				teamType CDATA #IMPLIED
				index CDATA #IMPLIED>
		<!ELEMENT door (#PCDATA)>
		<!ATTLIST door
				id CDATA #REQUIRED>
		<!ELEMENT zone (#PCDATA)>
		<!ATTLIST zone
				name CDATA #REQUIRED>
		<!ELEMENT point (#PCDATA)>
		<!ATTLIST point
				x CDATA #REQUIRED
				y CDATA #REQUIRED
				z CDATA #REQUIRED
				h CDATA #IMPLIED>
		<!ELEMENT npcLoc (#PCDATA)>
		<!ATTLIST npcLoc
				name CDATA #REQUIRED
				npc_id CDATA #REQUIRED
				x CDATA #REQUIRED
				y CDATA #REQUIRED
				z CDATA #REQUIRED
				h CDATA #IMPLIED>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/fight_club_maps/Protect The King Maps.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "maps.dtd">
<list>
	<map name="Giran Town">
		<parameter name="events" value="ProtectTheKing"/>
		<parameter name="teamsCount_DEFENDER" value="1"/>
		<parameter name="teamsCount_ATTACKER" value="1"/>
		<parameter name="minAllPlayers" value="1"/>
		<parameter name="maxAllPlayers" value="70"/>

		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="80184" y="150024" z="-3558"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="80040" y="151736" z="-3558"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="82456" y="150264" z="-3558"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="82328" y="148600" z="-3492"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="85800" y="148632" z="-3427"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="85768" y="149656" z="-3417"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="86792" y="147336" z="-3430"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="85432" y="146472" z="-3425"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="82552" y="144408" z="-3558"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="80760" y="143944" z="-3558"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="80568" y="145480" z="-3558"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="79608" y="147288" z="-3558"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="77864" y="149592" z="-3622"/>
		</objects>
		
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="81096" y="154760" z="-3509"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="77848" y="151032" z="-3602"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="75448" y="148072" z="-3533"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="78040" y="146232" z="-3622"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="79544" y="144328" z="-3570"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="82200" y="140664" z="-3613"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="90120" y="144584" z="-3432"/>
		</objects>
		
		<objects name="territory">
			<zone name="[FC_Around_Giran_Town]" />
		</objects>
	</map>

	<map name="Aden Town">
		<parameter name="events" value="ProtectTheKing"/>
		<parameter name="teamsCount_DEFENDER" value="1"/>
		<parameter name="teamsCount_ATTACKER" value="1"/>
		<parameter name="minAllPlayers" value="1"/>
		<parameter name="maxAllPlayers" value="70"/>
		
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="144728" y="29832" z="-2486"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="146728" y="28200" z="-2294"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="148216" y="28264" z="-2294"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="148248" y="26808" z="-2230"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="146728" y="26952" z="-2230"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="147448" y="23784" z="-2017"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="148552" y="23720" z="-2038"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="146312" y="23512" z="-2038"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="143928" y="23160" z="-2166"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="144952" y="20728" z="-2129"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="149944" y="20808" z="-2140"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="150600" y="22936" z="-2166"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="150696" y="27608" z="-2294"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="150024" y="29784" z="-2486"/>
		</objects>

		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="145896" y="31976" z="-2489"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="148632" y="31992" z="-2473"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="151880" y="26216" z="-2164"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="151880" y="23992" z="-2133"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="147416" y="18952" z="-1923"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="142904" y="25272" z="-2421"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="142776" y="27368" z="-2432"/>
		</objects>

		<objects name="territory">
			<zone name="[FC_Around_Aden_Town]" />
		</objects>
	</map>

	<map name="Primeval Isle">
		<parameter name="events" value="ProtectTheKing"/>
		<parameter name="teamsCount_DEFENDER" value="1"/>
		<parameter name="teamsCount_ATTACKER" value="1"/>
		<parameter name="minAllPlayers" value="1"/>
		<parameter name="maxAllPlayers" value="70"/>

		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="15128" y="-18792" z="-3200"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="18136" y="-19416" z="-3284"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="20840" y="-19640" z="-3306"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="22536" y="-17784" z="-2987"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="23640" y="-21336" z="-2576"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="25784" y="-17352" z="-2799"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="27672" y="-19064" z="-2452"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="29016" y="-17672" z="-2424"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="27560" y="-14408" z="-2653"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="28120" y="-12520" z="-2282"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="24280" y="-12952" z="-2514"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="22040" y="-6248" z="-2022"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="20440" y="-7720" z="-2583"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="18280" y="-9320" z="-2772"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="16376" y="-7080" z="-3184"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="12904" y="-9592" z="-3157"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="13800" y="-12600" z="-3121"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="13320" y="-15720" z="-2996"/>
		</objects>

		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="18248" y="-18136" z="-3238"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="20472" y="-17032" z="-3081"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="20248" y="-15064" z="-3098"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="17672" y="-15880" z="-3212"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="16040" y="-17112" z="-3262"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="15864" y="-13544" z="-3217"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="18232" y="-13560" z="-3129"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="17016" y="-11832" z="-3184"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="15592" y="-9720" z="-3286"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="20888" y="-9976" z="-2901"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="21336" y="-11864" z="-2767"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="24888" y="-11016" z="-2551"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="25976" y="-12872" z="-2607"/>
		</objects>
		<objects name="teamSpawns" teamType="ATTACKER">
			<point x="24904" y="-15992" z="-2798"/>
		</objects>

		<objects name="territory">
			<zone name="[FC_Primeval_Isle_Jungle]" />
		</objects>
	</map>

	<map name="Catacumb of the Witch">
		<parameter name="events" value="ProtectTheKing"/>
		<parameter name="teamsCount_DEFENDER" value="1"/>
		<parameter name="teamsCount_ATTACKER" value="1"/>
		<parameter name="minAllPlayers" value="1"/>
		<parameter name="maxAllPlayers" value="70"/>

		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="140792" y="79656" z="-5452"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="141864" y="79672" z="-5452"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="140808" y="81784" z="-5452"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
			<point x="140776" y="84280" z="-5452"/>
		</objects>
		<objects name="teamSpawns" teamType="DEFENDER">
