=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/npc/npc.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (npc)*>
<!ELEMENT npc (set|faction|skills|equip|rewardlist|teach_classes|minions|teleportlist|absorblist|ai_params|attributes)*>
<!ATTLIST npc
	id CDATA #REQUIRED
	template_id CDATA #IMPLIED
	name CDATA #REQUIRED
	title CDATA #REQUIRED>
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	id CDATA #REQUIRED
	level CDATA #REQUIRED>
<!ELEMENT faction (ignore)*>
<!ATTLIST faction
	name CDATA #REQUIRED
	range CDATA #REQUIRED>
<!ELEMENT ignore (#PCDATA)>
<!ATTLIST ignore
	npc_id CDATA #REQUIRED>
<!ELEMENT equip (rhand|lhand)*>
<!ELEMENT rhand (#PCDATA)>
<!ATTLIST rhand
	item_id CDATA #REQUIRED
	enchantLvl CDATA #IMPLIED>
<!ELEMENT lhand (#PCDATA)>
<!ATTLIST lhand
	item_id CDATA #REQUIRED>
<!ELEMENT teach_classes (class)*>
<!ELEMENT class (#PCDATA)>
<!ATTLIST class
	id CDATA #REQUIRED>
<!ELEMENT minions (minion)*>
<!ELEMENT minion (#PCDATA)>
<!ATTLIST minion
	npc_id CDATA #REQUIRED
	count CDATA #REQUIRED>
<!ELEMENT rewardlist (group|reward)*>
<!ATTLIST rewardlist
	type CDATA #REQUIRED>
<!ELEMENT group (reward)*>
<!ATTLIST group
	chance CDATA #IMPLIED>
<!ELEMENT reward (#PCDATA)>
<!ATTLIST reward
	chance CDATA #REQUIRED
	item_id CDATA #REQUIRED
	max CDATA #REQUIRED
	min CDATA #REQUIRED
	enchantLvl CDATA #IMPLIED>
<!ELEMENT teleportlist (sublist)*>
<!ELEMENT sublist (target)*>
<!ATTLIST sublist
	id CDATA #REQUIRED>
<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	item_id CDATA #REQUIRED
	loc CDATA #REQUIRED
        castle_id CDATA #IMPLIED
	name CDATA #REQUIRED
	price CDATA #REQUIRED
	StringName CDATA #REQUIRED
	StringNameLang CDATA #REQUIRED>
<!ELEMENT absorblist (absorb)*>
<!ELEMENT absorb (#PCDATA)>
<!ATTLIST absorb
	chance CDATA #REQUIRED
	cursed_chance CDATA #IMPLIED
	min_level CDATA #REQUIRED
	max_level CDATA #REQUIRED
	skill CDATA #IMPLIED
	type CDATA #REQUIRED>
<!ELEMENT ai_params (set)*>
<!ELEMENT attributes (attack|defence)*>
<!ELEMENT attack (#PCDATA)>
<!ATTLIST attack
	attribute CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT defence (#PCDATA)>
<!ATTLIST defence
	attribute CDATA #REQUIRED
	value CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/npc/32100-32199.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "npc.dtd">
<list>
	<npc id="32100" name="Tony the Cat" title="Event Manager">
		<set name="aggroRange" value="0" />
		<set name="ai_type" value="CharacterAI" />
		<set name="baseAtkRange" value="40" />
		<set name="baseCON" value="43" />
		<set name="baseCritRate" value="40" />
		<set name="baseDEX" value="30" />
		<set name="baseHpMax" value="2444.468" />
		<set name="baseHpRate" value="1" />
		<set name="baseHpReg" value="7.5" />
		<set name="baseINT" value="21" />
		<set name="baseMAtk" value="780" />
		<set name="baseMAtkSpd" value="500" />
		<set name="baseMDef" value="382" />
		<set name="baseMEN" value="20" />
		<set name="baseMpMax" value="1345.8" />
		<set name="baseMpReg" value="2.7" />
		<set name="basePAtk" value="1303" />
		<set name="basePAtkSpd" value="253" />
		<set name="basePDef" value="471" />
		<set name="baseRunSpd" value="120" />
		<set name="baseSTR" value="40" />
		<set name="baseShldDef" value="0" />
		<set name="baseShldRate" value="0" />
		<set name="baseWIT" value="20" />
		<set name="baseWalkSpd" value="48" />
		<set name="collision_height" value="15.0" />
		<set name="collision_radius" value="8.0" />
		<set name="level" value="70" />
		<set name="rewardExp" value="0" />
		<set name="rewardRp" value="0" />
		<set name="rewardSp" value="0" />
		<set name="shots" value="NONE" />
		<set name="texture" value="" />
		<set name="type" value="Npc" />
		<skills>
			<skill id="4416" level="7" />	<!--Spirits-->
		</skills>
		<attributes>
			<defence attribute="fire" value="150" />
			<defence attribute="water" value="150" />
			<defence attribute="wind" value="150" />
			<defence attribute="earth" value="150" />
			<defence attribute="holy" value="150" />
			<defence attribute="unholy" value="150" />
		</attributes>
	</npc>
	<npc id="32101" name="Tony the Cat" title="Event Manager">
		<set name="aggroRange" value="0" />
		<set name="ai_type" value="CharacterAI" />
		<set name="baseAtkRange" value="40" />
		<set name="baseCON" value="43" />
		<set name="baseCritRate" value="40" />
		<set name="baseDEX" value="30" />
		<set name="baseHpMax" value="2444.468" />
		<set name="baseHpRate" value="1" />
		<set name="baseHpReg" value="7.5" />
		<set name="baseINT" value="21" />
		<set name="baseMAtk" value="780" />
		<set name="baseMAtkSpd" value="500" />
		<set name="baseMDef" value="382" />
		<set name="baseMEN" value="20" />
		<set name="baseMpMax" value="1345.8" />
		<set name="baseMpReg" value="2.7" />
		<set name="basePAtk" value="1303" />
		<set name="basePAtkSpd" value="253" />
		<set name="basePDef" value="471" />
		<set name="baseRunSpd" value="120" />
		<set name="baseSTR" value="40" />
		<set name="baseShldDef" value="0" />
		<set name="baseShldRate" value="0" />
		<set name="baseWIT" value="20" />
		<set name="baseWalkSpd" value="48" />
		<set name="collision_height" value="15.0" />
		<set name="collision_radius" value="8.0" />
		<set name="level" value="70" />
		<set name="rewardExp" value="0" />
		<set name="rewardRp" value="0" />
		<set name="rewardSp" value="0" />
		<set name="shots" value="NONE" />
		<set name="texture" value="" />
		<set name="type" value="Npc" />
		<skills>
			<skill id="4416" level="7" />	<!--Spirits-->
		</skills>
		<attributes>
			<defence attribute="fire" value="150" />
			<defence attribute="water" value="150" />
			<defence attribute="wind" value="150" />
			<defence attribute="earth" value="150" />
			<defence attribute="holy" value="150" />
			<defence attribute="unholy" value="150" />
		</attributes>
	</npc>
	<npc id="32102" name="Tony the Cat" title="Event Manager">
		<set name="aggroRange" value="0" />
		<set name="ai_type" value="CharacterAI" />
		<set name="baseAtkRange" value="40" />
		<set name="baseCON" value="43" />
		<set name="baseCritRate" value="40" />
		<set name="baseDEX" value="30" />
		<set name="baseHpMax" value="2444.468" />
		<set name="baseHpRate" value="1" />
		<set name="baseHpReg" value="7.5" />
		<set name="baseINT" value="21" />
		<set name="baseMAtk" value="780" />
		<set name="baseMAtkSpd" value="500" />
		<set name="baseMDef" value="382" />
		<set name="baseMEN" value="20" />
		<set name="baseMpMax" value="1345.8" />
		<set name="baseMpReg" value="2.7" />
		<set name="basePAtk" value="1303" />
		<set name="basePAtkSpd" value="253" />
		<set name="basePDef" value="471" />
		<set name="baseRunSpd" value="120" />
		<set name="baseSTR" value="40" />
		<set name="baseShldDef" value="0" />
		<set name="baseShldRate" value="0" />
		<set name="baseWIT" value="20" />
		<set name="baseWalkSpd" value="48" />
		<set name="collision_height" value="15.0" />
		<set name="collision_radius" value="8.0" />
		<set name="level" value="70" />
		<set name="rewardExp" value="0" />
		<set name="rewardRp" value="0" />
		<set name="rewardSp" value="0" />
		<set name="shots" value="NONE" />
		<set name="texture" value="" />
		<set name="type" value="Npc" />
		<skills>
			<skill id="4416" level="7" />	<!--Spirits-->
		</skills>
		<attributes>
			<defence attribute="fire" value="150" />
			<defence attribute="water" value="150" />
			<defence attribute="wind" value="150" />
			<defence attribute="earth" value="150" />
			<defence attribute="holy" value="150" />
			<defence attribute="unholy" value="150" />
		</attributes>
	</npc>
	<npc id="32103" name="Telling the Cat" title="Event Manager">
		<set name="aggroRange" value="0" />
		<set name="ai_type" value="CharacterAI" />
		<set name="baseAtkRange" value="40" />
		<set name="baseCON" value="43" />
		<set name="baseCritRate" value="40" />
		<set name="baseDEX" value="30" />
		<set name="baseHpMax" value="2444.468" />
		<set name="baseHpRate" value="1" />
		<set name="baseHpReg" value="7.5" />
		<set name="baseINT" value="21" />
		<set name="baseMAtk" value="780" />
		<set name="baseMAtkSpd" value="500" />
		<set name="baseMDef" value="382" />
		<set name="baseMEN" value="20" />
		<set name="baseMpMax" value="1345.8" />
		<set name="baseMpReg" value="2.7" />
		<set name="basePAtk" value="1303" />
		<set name="basePAtkSpd" value="253" />
		<set name="basePDef" value="471" />
		<set name="baseRunSpd" value="120" />
		<set name="baseSTR" value="40" />
		<set name="baseShldDef" value="0" />
		<set name="baseShldRate" value="0" />
		<set name="baseWIT" value="20" />
		<set name="baseWalkSpd" value="48" />
		<set name="collision_height" value="15.0" />
		<set name="collision_radius" value="8.0" />
		<set name="level" value="70" />
		<set name="rewardExp" value="0" />
		<set name="rewardRp" value="0" />
		<set name="rewardSp" value="0" />
		<set name="shots" value="NONE" />
		<set name="texture" value="" />
		<set name="type" value="Npc" />
		<skills>
			<skill id="4416" level="7" />	<!--Spirits-->
		</skills>
		<attributes>
			<defence attribute="fire" value="150" />
			<defence attribute="water" value="150" />
			<defence attribute="wind" value="150" />
			<defence attribute="earth" value="150" />
			<defence attribute="holy" value="150" />
			<defence attribute="unholy" value="150" />
		</attributes>
	</npc>
	<npc id="32104" name="Vervato" title="">
		<set name="aggroRange" value="0" />
		<set name="ai_type" value="CharacterAI" />
		<set name="baseAtkRange" value="40" />
		<set name="baseCON" value="43" />
		<set name="baseCritRate" value="40" />
		<set name="baseDEX" value="30" />
		<set name="baseHpMax" value="2444.468" />
		<set name="baseHpRate" value="1" />
		<set name="baseHpReg" value="7.5" />
		<set name="baseINT" value="21" />
		<set name="baseMAtk" value="780" />
		<set name="baseMAtkSpd" value="500" />
		<set name="baseMDef" value="382" />
		<set name="baseMEN" value="20" />
		<set name="baseMpMax" value="1345.8" />
		<set name="baseMpReg" value="2.7" />
		<set name="basePAtk" value="1303" />
		<set name="basePAtkSpd" value="253" />
		<set name="basePDef" value="471" />
		<set name="baseRunSpd" value="132" />
		<set name="baseSTR" value="40" />
		<set name="baseShldDef" value="0" />
		<set name="baseShldRate" value="0" />
		<set name="baseWIT" value="20" />
		<set name="baseWalkSpd" value="88" />
		<set name="collision_height" value="33.0" />
		<set name="collision_radius" value="25.0" />
		<set name="level" value="70" />
		<set name="rewardExp" value="0" />
		<set name="rewardRp" value="0" />
		<set name="rewardSp" value="0" />
		<set name="shots" value="NONE" />
		<set name="texture" value="" />
		<set name="type" value="Npc" />
		<skills>
			<skill id="4416" level="6" />	<!--Humanoids-->
		</skills>
		<attributes>
			<defence attribute="fire" value="150" />
			<defence attribute="water" value="150" />
			<defence attribute="wind" value="150" />
			<defence attribute="earth" value="150" />
			<defence attribute="holy" value="150" />
			<defence attribute="unholy" value="150" />
		</attributes>
	</npc>
	<npc id="32105" name="Dinn" title="">
		<set name="aggroRange" value="0" />
		<set name="ai_type" value="CharacterAI" />
		<set name="baseAtkRange" value="40" />
		<set name="baseCON" value="43" />
		<set name="baseCritRate" value="40" />
		<set name="baseDEX" value="30" />
		<set name="baseHpMax" value="2444.468" />
		<set name="baseHpRate" value="1" />
		<set name="baseHpReg" value="7.5" />
		<set name="baseINT" value="21" />
		<set name="baseMAtk" value="780" />
		<set name="baseMAtkSpd" value="500" />
		<set name="baseMDef" value="382" />
		<set name="baseMEN" value="20" />
		<set name="baseMpMax" value="1345.8" />
		<set name="baseMpReg" value="2.7" />
		<set name="basePAtk" value="1303" />
		<set name="basePAtkSpd" value="253" />
		<set name="basePDef" value="471" />
		<set name="baseRunSpd" value="132" />
		<set name="baseSTR" value="40" />
		<set name="baseShldDef" value="0" />
		<set name="baseShldRate" value="0" />
		<set name="baseWIT" value="20" />
		<set name="baseWalkSpd" value="88" />
		<set name="collision_height" value="23.0" />
		<set name="collision_radius" value="8.0" />
		<set name="level" value="70" />
