=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/premium/premium.dtd
<?xml version='1.0' encoding='utf-8'?>
<!ELEMENT list (premium)*>
<!ELEMENT premium (rate|price|gifts|time)*>
<!ATTLIST premium
	id CDATA #REQUIRED
	name CDATA #REQUIRED
	icon CDATA #REQUIRED>
<!ELEMENT rate (#PCDATA)>
<!ATTLIST rate
	type CDATA #REQUIRED
	value CDATA #REQUIRED>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price
	id CDATA #REQUIRED
	count CDATA #REQUIRED>
<!ELEMENT gifts (gift)*>
<!ELEMENT gift (#PCDATA)>
<!ATTLIST gift
	id CDATA #REQUIRED
	count CDATA #REQUIRED
	removable CDATA #REQUIRED>
<!ELEMENT time (#PCDATA)>
<!ATTLIST time
	days CDATA #REQUIRED
	hours CDATA #REQUIRED
	minutes CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/premium/premium.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE list SYSTEM "premium.dtd">
<list>
	<premium id="1" name="Experience Rate" icon="icon.etc_exp_point_i00">
		<rate type="EXP" value="1.50"/>
		<rate type="SP" value="1.50"/>
		<rate type="SIEGE" value="1."/>
		<rate type="ADENA" value="1."/>
		<rate type="DROP" value="1."/>
		<rate type="SPOIL" value="1."/>
		<rate type="WEIGHT_LIMIT" value="1."/>
		<rate type="CRAFT" value="3"/>
		<rate type="MASTERWORK_CRAFT" value="1"/>
		<rate type="ATTRIBUTE" value="10"/>
		<gifts>
			<gift id="20970" count="1" removable="true"/>
			<gift id="20340" count="1" removable="false"/>
			<gift id="20346" count="1" removable="false"/>
		</gifts>
		<time days="7" hours="0" minutes="0"/>
		<price id="37000" count="30"/>
	</premium>
	<premium id="2" name="Big Rate" icon="branchsys2.s_g_fantastic_magic">
		<rate type="EXP" value="1.40"/>
		<rate type="SP" value="1.40"/>
		<rate type="SIEGE" value="1.20"/>
		<rate type="ADENA" value="1.25"/>
		<rate type="DROP" value="1.30"/>
		<rate type="SPOIL" value="1.15"/>
		<rate type="WEIGHT_LIMIT" value="1.25"/>
		<rate type="CRAFT" value="3"/>
		<rate type="MASTERWORK_CRAFT" value="1"/>
		<rate type="ATTRIBUTE" value="10"/>
		<gifts>
			<gift id="20970" count="1" removable="true"/>
		</gifts>
		<time days="1" hours="0" minutes="0"/>
		<price id="37000" count="30"/>
	</premium>
	<premium id="3" name="Fire Rate" icon="branchsys2.skill20006">
		<rate type="EXP" value="1.43"/>
		<rate type="SP" value="1.43"/>
		<rate type="SIEGE" value="1.23"/>
		<rate type="ADENA" value="1.27"/>
		<rate type="DROP" value="1.33"/>
		<rate type="SPOIL" value="1.17"/>
		<rate type="WEIGHT_LIMIT" value="1.40"/>
		<rate type="CRAFT" value="6"/>
		<rate type="MASTERWORK_CRAFT" value="3"/>
		<rate type="ATTRIBUTE" value="10"/>
		<gifts>
			<gift id="20970" count="1" removable="true"/>
			<gift id="6577" count="1" removable="false"/>
			<gift id="6578" count="1" removable="false"/>
		</gifts>
		<time days="7" hours="0" minutes="0"/>
		<price id="37000" count="100"/>
	</premium>
	<premium id="4" name="Fury Rate" icon="branchsys2.br_skill1561">
		<rate type="EXP" value="1.45"/>
		<rate type="SP" value="1.45"/>
		<rate type="SIEGE" value="1.25"/>
		<rate type="ADENA" value="1.30"/>
		<rate type="DROP" value="1.35"/>
		<rate type="SPOIL" value="1.19"/>
		<rate type="WEIGHT_LIMIT" value="1.50"/>
		<rate type="CRAFT" value="8"/>
		<rate type="MASTERWORK_CRAFT" value="5"/>
		<rate type="ATTRIBUTE" value="10"/>
		<gifts>
			<gift id="20970" count="1" removable="true"/>
			<gift id="6577" count="3" removable="false"/>
			<gift id="6578" count="3" removable="false"/>
		</gifts>
		<time days="30" hours="0" minutes="0"/>
		<price id="37000" count="250"/>
	</premium>
	<premium id="5" name="Ultra Rate" icon="branchsys2.br_vitality_day_i00">
		<rate type="EXP" value="1.55"/>
		<rate type="SP" value="1.55"/>
		<rate type="SIEGE" value="1.35"/>
		<rate type="ADENA" value="1.40"/>
		<rate type="DROP" value="1.45"/>
		<rate type="SPOIL" value="1.29"/>
		<rate type="WEIGHT_LIMIT" value="1.60"/>
		<rate type="CRAFT" value="10"/>
		<rate type="MASTERWORK_CRAFT" value="11"/>
		<rate type="ATTRIBUTE" value="10"/>
		<gifts>
			<gift id="20970" count="1" removable="true"/>
			<gift id="6577" count="7" removable="false"/>
			<gift id="6578" count="7" removable="false"/>
		</gifts>
		<time days="60" hours="0" minutes="0"/>
		<price id="37000" count="400"/>
	</premium>
</list>
