=== TerryGomes/Projeto_H5_Custon/Projeto_H5/dist/gameserver/data/instances/instances.dtd
<!ELEMENT list (instance)*>
	<!ELEMENT instance (collapse|level|party|return|teleport|remove|give|quest|reuse|geodata|spawns|doors|zones|add_parameters)*>
	<!ATTLIST instance
			maxChannels CDATA #REQUIRED
			collapseIfEmpty CDATA #REQUIRED
			dispelBuffs CDATA #IMPLIED
			id CDATA #REQUIRED
			name CDATA #REQUIRED
			resetReuse CDATA #IMPLIED
			respawn CDATA #IMPLIED
			sharedReuseGroup CDATA #IMPLIED
			timelimit CDATA #IMPLIED>
	<!ELEMENT collapse (#PCDATA)>
	<!ATTLIST collapse
		on-party-dismiss CDATA #REQUIRED
		timer CDATA #REQUIRED>
	<!ELEMENT level (#PCDATA)>
	<!ATTLIST level
		max CDATA #REQUIRED
		min CDATA #REQUIRED>
	<!ELEMENT party (#PCDATA)>
	<!ATTLIST party
		max CDATA #REQUIRED
		min CDATA #REQUIRED>
	<!ELEMENT return (#PCDATA)>
	<!ATTLIST return
		loc CDATA #REQUIRED>
	<!ELEMENT teleport (#PCDATA)>
	<!ATTLIST teleport
		loc CDATA #REQUIRED>
		<!ELEMENT remove (#PCDATA)>
	<!ATTLIST remove
		count CDATA #REQUIRED
		itemId CDATA #REQUIRED
		necessary CDATA #REQUIRED>
	<!ELEMENT give (#PCDATA)>
		<!ATTLIST give
		count CDATA #REQUIRED
		itemId CDATA #REQUIRED>
	<!ELEMENT quest (#PCDATA)>
	<!ATTLIST quest
		id CDATA #REQUIRED>
	<!ELEMENT reuse (#PCDATA)>
	<!ATTLIST reuse
		resetReuse CDATA #REQUIRED
		setUponEntry CDATA #REQUIRED
		sharedReuseGroup CDATA #REQUIRED>
	<!ELEMENT geodata (#PCDATA)>
	<!ATTLIST geodata
		map CDATA #REQUIRED>
	<!ELEMENT spawns (spawn|group)*>
	<!ELEMENT spawn (coords)*>
	<!ATTLIST spawn
		count CDATA #IMPLIED
		mobId CDATA #REQUIRED
		respawn CDATA #IMPLIED
		respawnRnd CDATA #IMPLIED
		type CDATA #REQUIRED>
	<!ELEMENT coords (#PCDATA)>
	<!ATTLIST coords
		loc CDATA #REQUIRED>

<!ELEMENT group (#PCDATA)>
<!ATTLIST group
	name CDATA #REQUIRED
	spawned CDATA #IMPLIED>

<!ELEMENT doors (door)*>
<!ELEMENT door (#PCDATA)>
<!ATTLIST door
	id CDATA #REQUIRED
	opened CDATA #IMPLIED
	invul CDATA #IMPLIED>

<!ELEMENT zones (zone)*>
<!ELEMENT zone (#PCDATA)>
<!ATTLIST zone
	name CDATA #REQUIRED
	active CDATA #IMPLIED>

<!ELEMENT add_parameters (param)*>
<!ELEMENT param (#PCDATA)>
<!ATTLIST param
	name CDATA #REQUIRED
	value CDATA #REQUIRED>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/instances/[044] Pailaka Devils Legacy.xml
<!DOCTYPE list SYSTEM "instances.dtd">
<list>
	<!-- Pailaka Devils Legacy (Level 61-67) -->
	<instance id="44" name="Pailaka (Devil's Isle)" maxChannels="15" collapseIfEmpty="10" timelimit="180">
		<collapse on-party-dismiss="true" timer="60"/>
		<level min="61" max="67"/>
		<party min="1" max="1"/>
		<return loc="85176 147592 -3408"/>
		<teleport loc="76438 -219035 -3752"/>
		<remove itemId="0" count="0" necessary="false"/>
		<give itemId="0" count="0"/>
		<quest id="129"/>
		<reuse resetReuse="30 6 * * *" setUponEntry="true" sharedReuseGroup="0"/>
		<spawns>
			<spawn mobId="18622" type="point" respawn="120">
				<coords loc="79189 -210458 -3753 8353"/>
				<coords loc="77923 -205411 -3585 32501"/>
				<coords loc="78213 -205549 -3585 13028"/>
				<coords loc="79420 -209913 -3753 24575"/>
				<coords loc="79100 -205721 -3585 8231"/>
				<coords loc="79254 -205268 -3585 3283"/>
			</spawn>
			<spawn mobId="18623" type="point" respawn="0">
				<coords loc="87222 -209251 -3747 41489"/>
				<coords loc="87964 -212354 -4222 49807"/>
				<coords loc="86829 -209914 -4058 50941"/>
				<coords loc="87018 -209216 -3747 49151"/>
				<coords loc="87888 -212418 -4224 40068"/>
				<coords loc="86742 -209412 -3826 1075"/>
			</spawn>
			<spawn mobId="18624" type="point" respawn="0">
				<coords loc="79486 -215189 -3586 55522"/>
				<coords loc="79611 -215670 -3573 3572"/>
				<coords loc="76454 -215338 -3697 62044"/>
				<coords loc="78906 -213577 -3745 32890"/>
				<coords loc="76759 -215785 -3713 11152"/>
				<coords loc="74707 -215828 -3713 64106"/>
				<coords loc="78818 -212675 -3753 49009"/>
				<coords loc="78286 -214185 -3649 1605"/>
				<coords loc="74678 -213426 -3713 45938"/>
				<coords loc="78330 -214027 -3674 61972"/>
				<coords loc="75010 -215381 -3713 58176"/>
				<coords loc="80271 -216861 -3588 33758"/>
				<coords loc="79815 -216744 -3575 39237"/>
				<coords loc="79403 -220622 -3624 31252"/>
				<coords loc="79911 -216924 -3572 32563"/>
				<coords loc="78460 -213654 -3733 34295"/>
				<coords loc="79361 -220351 -3630 35178"/>
				<coords loc="82238 -217209 -3729 46104"/>
				<coords loc="82651 -217111 -3729 50219"/>
				<coords loc="78997 -220017 -3628 40111"/>
				<coords loc="83245 -216852 -3729 56758"/>
				<coords loc="83217 -215436 -3729 53234"/>
				<coords loc="79296 -219808 -3641 42225"/>
				<coords loc="82393 -215414 -3729 54126"/>
				<coords loc="78512 -218154 -3697 57046"/>
				<coords loc="78296 -218497 -3697 58070"/>
			</spawn>
			<spawn mobId="18625" type="point" respawn="0">
				<coords loc="79342 -205928 -3585 62817"/>
				<coords loc="79625 -208324 -3753 49477"/>
				<coords loc="79422 -206109 -3585 19137"/>
				<coords loc="79886 -205132 -3585 37757"/>
				<coords loc="79058 -205470 -3585 24122"/>
				<coords loc="78857 -205432 -3585 26526"/>
				<coords loc="78935 -205219 -3585 27835"/>
				<coords loc="78918 -205266 -3585 24094"/>
				<coords loc="79167 -205395 -3585 27931"/>
				<coords loc="79414 -205263 -3585 33316"/>
				<coords loc="81320 -206750 -3585 11373"/>
				<coords loc="81573 -207488 -3585 12160"/>
				<coords loc="79044 -207967 -3753 21699"/>
				<coords loc="81631 -208349 -3585 45651"/>
				<coords loc="79587 -207997 -3756 15805"/>
				<coords loc="82232 -205882 -3585 21479"/>
				<coords loc="79368 -208051 -3753 15162"/>
				<coords loc="82001 -205932 -3585 23053"/>
				<coords loc="82343 -205311 -3585 29058"/>
				<coords loc="79465 -205126 -3585 29412"/>
				<coords loc="81931 -208453 -3585 37604"/>
				<coords loc="79295 -210439 -3753 55955"/>
				<coords loc="79522 -209584 -3756 29801"/>
				<coords loc="79265 -209751 -3753 40463"/>
				<coords loc="79301 -210104 -3753 52776"/>
				<coords loc="79451 -210279 -3753 56543"/>
				<coords loc="79686 -209965 -3756 12073"/>
				<coords loc="79888 -215504 -3593 63852"/>
				<coords loc="78530 -218248 -3697 56462"/>
				<coords loc="79420 -209698 -3753 25422"/>
				<coords loc="86624 -219483 -3721 29643"/>
				<coords loc="83051 -216042 -3729 57233"/>
				<coords loc="79143 -210240 -3756 46228"/>
				<coords loc="83640 -219434 -4004 24575"/>
				<coords loc="83412 -219389 -4004 8804"/>
				<coords loc="78855 -214065 -3669 53553"/>
				<coords loc="78780 -214164 -3653 60512"/>
				<coords loc="79299 -208457 -3753 36821"/>
				<coords loc="77356 -205470 -3585 55355"/>
				<coords loc="77775 -205628 -3585 50928"/>
				<coords loc="77716 -205324 -3585 55863"/>
				<coords loc="79664 -208559 -3753 61651"/>
				<coords loc="78317 -208988 -3921 46182"/>
				<coords loc="77932 -208870 -3927 49151"/>
				<coords loc="77612 -209977 -3908 46498"/>
				<coords loc="78055 -209934 -3908 48076"/>
				<coords loc="78584 -212812 -3753 666"/>
				<coords loc="78720 -212881 -3753 48947"/>
				<coords loc="78844 -213375 -3753 41833"/>
				<coords loc="78836 -213555 -3748 29591"/>
				<coords loc="79457 -208682 -3753 20607"/>
			</spawn>
			<spawn mobId="18626" type="point" respawn="0">
				<coords loc="83267 -213306 -3345 33653"/>
				<coords loc="82833 -213431 -3345 37385"/>
				<coords loc="81171 -212063 -3425 42114"/>
				<coords loc="80936 -212424 -3425 54292"/>
				<coords loc="83460 -213867 -3345 32670"/>
				<coords loc="83089 -213820 -3345 20229"/>
				<coords loc="81099 -213800 -3348 58641"/>
				<coords loc="81092 -213544 -3345 15086"/>
				<coords loc="80644 -213255 -3345 26956"/>
				<coords loc="80249 -213787 -3345 3243"/>
				<coords loc="80772 -212208 -3425 9977"/>
				<coords loc="80642 -212382 -3425 5139"/>
				<coords loc="81621 -209250 -3585 9457"/>
				<coords loc="81754 -208403 -3585 38697"/>
				<coords loc="81905 -208811 -3585 26769"/>
				<coords loc="81173 -207246 -3585 7437"/>
				<coords loc="81637 -207101 -3585 2612"/>
				<coords loc="81756 -207296 -3585 2762"/>
				<coords loc="82104 -207234 -3588 3742"/>
				<coords loc="82400 -205624 -3585 19198"/>
				<coords loc="81922 -209050 -3585 24780"/>
				<coords loc="82279 -205774 -3585 26243"/>
				<coords loc="83209 -211920 -3425 34872"/>
				<coords loc="82759 -212205 -3425 44874"/>
				<coords loc="82631 -212425 -3425 52034"/>
				<coords loc="82614 -212207 -3428 53485"/>
			</spawn>
			<spawn mobId="18627" type="point" respawn="0">
				<coords loc="86049 -216957 -2465 41586"/>
				<coords loc="85355 -214573 -2465 55310"/>
				<coords loc="85134 -216585 -2465 7334"/>
				<coords loc="84935 -216565 -2465 16549"/>
				<coords loc="84821 -216989 -2465 46401"/>
				<coords loc="85362 -217332 -2465 12227"/>
				<coords loc="86153 -215291 -2465 10142"/>
				<coords loc="86361 -215239 -2464 2555"/>
				<coords loc="86111 -215590 -2468 38573"/>
				<coords loc="86400 -215389 -2464 3792"/>
				<coords loc="84941 -214854 -2465 17871"/>
				<coords loc="86214 -216540 -2468 31298"/>
				<coords loc="86260 -216719 -2465 63227"/>
				<coords loc="86558 -216544 -2465 46930"/>
				<coords loc="85056 -215233 -2465 24159"/>
				<coords loc="84372 -214622 -3025 26546"/>
				<coords loc="84178 -213369 -3345 46395"/>
				<coords loc="84441 -213264 -3345 59962"/>
				<coords loc="82914 -215701 -2708 49730"/>
				<coords loc="84378 -213761 -3345 20607"/>
				<coords loc="83045 -215412 -2705 50043"/>
				<coords loc="84599 -213811 -3345 38965"/>
				<coords loc="82800 -215391 -2705 36991"/>
				<coords loc="82449 -215572 -2705 39097"/>
				<coords loc="85325 -215400 -2465 20126"/>
				<coords loc="84543 -214290 -3025 31692"/>
			</spawn>
			<spawn mobId="18629" type="point" respawn="0">
				<coords loc="80699 -219268 -3521 11650"/>
			</spawn>
			<spawn mobId="18630" type="point" respawn="0">
				<coords loc="77981 -205910 -3585 1186"/>
			</spawn>
			<spawn mobId="18631" type="point" respawn="0">
				<coords loc="82629 -209487 -3585 142"/>
			</spawn>
			<spawn mobId="18632" type="point" respawn="0">
				<coords loc="82387 -217356 -2705 64839"/>
			</spawn>
			<spawn mobId="18633" type="point" respawn="0">
				<coords loc="87881 -209137 -3747 32525"/>
			</spawn>
			<spawn mobId="32495" type="point" respawn="60">
				<coords loc="80069 -213849 -3345 2092"/>
				<coords loc="75940 -205504 -3688 47671"/>
				<coords loc="74933 -212142 -3713 49251"/>
				<coords loc="77032 -213457 -3713 33057"/>
				<coords loc="76248 -216565 -3658 11667"/>
				<coords loc="78570 -216344 -3593 32767"/>
				<coords loc="80152 -214362 -3593 32591"/>
				<coords loc="87113 -219160 -3700 36919"/>
				<coords loc="82069 -215191 -3729 0"/>
				<coords loc="81474 -218808 -3521 36284"/>
				<coords loc="85297 -214369 -2465 48897"/>
				<coords loc="82079 -215290 -2705 356"/>
				<coords loc="77317 -205198 -3585 55710"/>
				<coords loc="85090 -214689 -3025 33482"/>
				<coords loc="86736 -217103 -2465 16383"/>
				<coords loc="85187 -213664 -3345 32091"/>
				<coords loc="82764 -217077 -2705 0"/>
				<coords loc="86020 -220575 -3729 14459"/>
				<coords loc="86058 -215531 -2465 65255"/>
				<coords loc="85263 -217540 -2465 19243"/>
				<coords loc="83316 -212502 -3425 31644"/>
				<coords loc="80352 -212518 -3425 707"/>
			</spawn>
			<spawn mobId="32501" type="point" respawn="0">
				<coords loc="77015 -218933 -3757 31871"/>
			</spawn>
			<spawn mobId="32508" type="point" respawn="0">
				<coords loc="82736 -205312 -3585 32767"/>
				<coords loc="81719 -210866 -3585 10557"/>
				<coords loc="78696 -214888 -3593 50891"/>
			</spawn>
		</spawns>
		<zones>
			<zone name="[22_11_water1]" active="true"/>
			<zone name="[21_25_water1]" active="true"/>
		</zones>
	</instance>
</list>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/instances/[002] Urban Area.xml
<!DOCTYPE list SYSTEM "instances.dtd">
<list>
    <!-- Hellbound: Urban Area -->
    <instance id="2" name="Urban Area" maxChannels="10" collapseIfEmpty="10" timelimit="30" dispelBuffs="false">
        <collapse on-party-dismiss="true" timer="60"/>
        <level min="78" max="85"/>
        <party min="2" max="9"/>
        <return loc="13725 255403 -2023"/>
        <teleport loc="14119 255443 -2016"/>
        <remove itemId="0" count="0" necessary="false"/>
        <give itemId="0" count="0"/>
        <quest id="0"/>
        <reuse resetReuse="* * * * *" setUponEntry="true" sharedReuseGroup="0"/>
        <spawns>
            <!-- Town Guard -->
            <spawn mobId="22359" count="5" respawn="120" type="loc">
                <coords loc="14760 254280 -2047 -2047"/>
                <coords loc="13992 254184 -2047 -2047"/>
                <coords loc="14008 253448 -2047 -2047"/>
                <coords loc="14776 253432 -2047 -2047"/>
            </spawn>
            <spawn mobId="22359" count="5" respawn="120" type="loc">
                <coords loc="14872 251848 -2030 -1930"/>
                <coords loc="14904 250824 -1973 -1873"/>
                <coords loc="15800 250824 -1972 -1872"/>
                <coords loc="15880 251800 -2033 -1933"/>
            </spawn>
            <spawn mobId="22359" count="5" respawn="120" type="loc">
                <coords loc="16536 254520 -2081 -1981"/>
                <coords loc="15704 254552 -2074 -1974"/>
                <coords loc="16072 255640 -2054 -1954"/>
                <coords loc="16728 255368 -2099 -1999"/>
            </spawn>
            <spawn mobId="22359" count="5" respawn="120" type="loc">
                <coords loc="18904 256312 -2125 -2025"/>
                <coords loc="18920 255704 -2062 -1962"/>
                <coords loc="19544 255640 -2095 -1995"/>
                <coords loc="19496 256344 -2125 -2025"/>
            </spawn>
            <spawn mobId="22359" count="12" respawn="120" type="loc">
                <coords loc="21384 254680 -2035 -1935"/>
                <coords loc="17720 254664 -2047 -1947"/>
                <coords loc="17656 252120 -2047 -1947"/>
                <coords loc="20408 252168 -2047 -1947"/>
                <coords loc="21480 252840 -2046 -1946"/>
            </spawn>
            <spawn mobId="22359" count="5" respawn="120" type="loc">
                <coords loc="19640 251192 -2047 -1947"/>
                <coords loc="20760 251192 -2047 -1947"/>
                <coords loc="20760 250168 -2005 -1905"/>
                <coords loc="19256 250376 -2047 -1947"/>
            </spawn>
            <!-- Town Patrolman -->
            <spawn mobId="22360" respawn="120" type="point">
                <coords loc="14759 254626 -2033 11781"/>
                <coords loc="15626 250586 -1932 56089"/>
                <coords loc="16163 254466 -2082 47441"/>
                <coords loc="17106 256208 -2064 25958"/>
                <coords loc="18051 256253 -2101 34402"/>
                <coords loc="21894 252039 -2019 9185"/>
                <coords loc="22194 251956 -2017 17645"/>
                <coords loc="22678 253887 -2016 8992"/>
                <coords loc="19914 250973 -2020 13028"/>
                <coords loc="17662 251962 -2020 37829"/>
                <coords loc="20301 253744 -2033 63557"/>
                <coords loc="19427 252757 -2033 35158"/>
            </spawn>
            <!-- Native Prisoner -->
            <spawn mobId="32358" type="point">
                <coords loc="14024 254872 -2035 -1"/>
                <coords loc="15064 253768 -2038 -1"/>
                <coords loc="14120 253112 -2039 -1"/>
                <coords loc="13944 251880 -1962 -1"/>
                <coords loc="14200 250408 -1966 -1"/>
                <coords loc="16584 253912 -2060 -1"/>
                <coords loc="15576 255560 -2041 -1"/>
                <coords loc="16280 256264 -2043 -1"/>
                <coords loc="20120 256200 -2116 -1"/>
                <coords loc="19832 255112 -2034 -1"/>
                <coords loc="17640 255080 -2045 -1"/>
                <coords loc="17208 253000 -2041 -1"/>
                <coords loc="17528 250456 -1948 -1"/>
                <coords loc="18904 251288 -2035 -1"/>
                <coords loc="21256 250488 -2006 -1"/>
                <coords loc="21304 251128 -2034 -1"/>
                <coords loc="18888 251800 -2037 -1"/>
                <coords loc="20968 251736 -2033 -1"/>
                <coords loc="21976 253368 -2040 -1"/>
                <coords loc="22008 254008 -2036 -1"/>
            </spawn>
            <!-- Amaskari -->
            <spawn mobId="22449" type="point">
                <coords loc="19496 253125 -2030 44398"/>
            </spawn>
            <!-- Moonlight Tombstone -->
            <spawn mobId="32343" type="point">
                <coords loc="19720 250056 -2016 17184"/>
            </spawn>
            <!-- Steel Citadel Keymaster -->
            <spawn mobId="22361" type="rnd">
                <coords loc="14044 254892 -2035 -1"/>
                <coords loc="15084 253788 -2038 -1"/>
                <coords loc="14140 253132 -2039 -1"/>
                <coords loc="13964 251860 -1962 -1"/>
                <coords loc="14220 250428 -1966 -1"/>
                <coords loc="16564 253932 -2060 -1"/>
                <coords loc="15596 255580 -2041 -1"/>
                <coords loc="16260 256284 -2043 -1"/>
                <coords loc="20140 256220 -2116 -1"/>
                <coords loc="19852 255132 -2034 -1"/>
                <coords loc="17660 255060 -2045 -1"/>
                <coords loc="17228 253020 -2041 -1"/>
                <coords loc="17548 250476 -1948 -1"/>
                <coords loc="18924 251268 -2035 -1"/>
                <coords loc="21276 250468 -2006 -1"/>
                <coords loc="21324 251148 -2034 -1"/>
                <coords loc="18868 251820 -2037 -1"/>
                <coords loc="20948 251756 -2033 -1"/>
                <coords loc="21996 253388 -2040 -1"/>
                <coords loc="22028 254028 -2036 -1"/>
            </spawn>
        </spawns>
    </instance>
</list>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/instances/[070] Kamaloka, Hall of the Abyss.xml
<!DOCTYPE list SYSTEM "instances.dtd">
<list>
	<!-- Town of Schuttgart: NPC Vishotsky (Level 66)  -->
	<instance id="70" name="Kamaloka, Hall of the Abyss" maxChannels="10" collapseIfEmpty="10" timelimit="30" dispelBuffs="false">
		<collapse on-party-dismiss="true" timer="60"/>
		<level min="61" max="71"/>
		<party min="2" max="6"/>
		<return loc="85962 -142187 -1344"/>
		<teleport loc="23648 -213600 -8000"/>
		<remove itemId="0" count="0" necessary="false"/>
		<give itemId="0" count="0"/>
		<quest id="0"/>
		<reuse resetReuse="30 6 * * *" setUponEntry="false" sharedReuseGroup="1"/>
		<add_parameters>
			<param name="tele_device_loc" value="23655 -213048 -8000"/>
		</add_parameters>
		<spawns>
			<!-- Kel Bilette -->
			<spawn mobId="18573" type="loc">
				<coords loc="23459 -212855 -8000 -8000"/>
				<coords loc="23459 -213255 -8000 -8000"/>
				<coords loc="23859 -213255 -8000 -8000"/>
				<coords loc="23859 -212855 -8000 -8000"/>
			</spawn>
			<!-- Follower of Bilette -->
			<spawn mobId="18574" count="4" respawn="30" type="loc">
				<coords loc="23459 -212855 -8000 -8000"/>
				<coords loc="23459 -213255 -8000 -8000"/>
				<coords loc="23859 -213255 -8000 -8000"/>
				<coords loc="23859 -212855 -8000 -8000"/>
			</spawn>
		</spawns>
	</instance>
</list>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/instances/[605] Korean Style.xml
<!DOCTYPE list SYSTEM "instances.dtd">
<list>
	<instance id="605" name="KoreanMap3" maxChannels="40" collapseIfEmpty="1" timelimit="120" dispelBuffs="false">
		<level min="1" max="85"/>
		<party min="1" max="1"/>
		<add_parameters>
			<param name="Right1" value="-19576, 280024, -13376, 0" />
			<param name="Right2" value="-19576, 277160, -13376, 0" />
			<param name="Left1" value="-18488, 280024, -13376, 32767" />
			<param name="Left2" value="-18488, 277160, -13376, 32767" />
			<param name="RightCenter" value="-19016, 278104, -13376" />
			<param name="LeftCenter" value="-19016, 279064, -13376" />
		</add_parameters>
		<zones>
			<zone name="[whole_world]" active="true"/>
		</zones>
	</instance>
</list>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/instances/[149] Stadium of Hero's Vestiges.xml
<!DOCTYPE list SYSTEM "instances.dtd">
<list>
	<instance id="149" name="Olympiad" maxChannels="40" collapseIfEmpty="1" timelimit="60" dispelBuffs="true">
		<level min="1" max="85"/>
		<party min="1" max="1"/>
		<geodata map="17_10"/>
		<teleport loc="-89176 -239352 -8474 0" />
		<teleport loc="-87000 -239352 -8474 0" />
		<teleport loc="-87382 -238952 -8474 0" />
		<doors>
			<door id="17100201"/>
			<door id="17100202"/>
		</doors>
		<spawns>
			<group name="olympiad_149_buffers" spawned="false"/>
		</spawns>
		<zones>
			<zone name="[olympiad_arena_149]" active="true"/>
		</zones>
	</instance>
</list>

=== TerryGomes/Projeto_H5_Custon/dist/gameserver/data/instances/[145] Girl of Doubt - Franz.xml
<!DOCTYPE list SYSTEM "instances.dtd">
<list>
	<!-- SSQ - Girl of Doubt, Franz -->
	<instance id="145" name="Girl of Doubt, Franz" maxChannels="20" collapseIfEmpty="1" timelimit="30" dispelBuffs="false" respawn="60">
		<collapse on-party-dismiss="true" timer="60"/>
		<level min="81" max="85"/>
		<return loc="147020 23775 -1984"/>
		<teleport loc="-23743 -8947 -5384"/>
		<remove itemId="0" count="0" necessary="false"/>
		<give itemId="0" count="0"/>
		<quest id="10292"/>
		<reuse resetReuse="* * * * *" setUponEntry="true" sharedReuseGroup="0"/>
		<spawns>
			<spawn mobId="32597" type="point" respawn="0">
				<coords loc="-23976 -8968 -5384 0"/>
			</spawn>
			<spawn mobId="32617" type="point" respawn="0">
				<coords loc="-23960 -8888 -5384 0"/>
			</spawn>
		</spawns>
	</instance>
</list>
